import { db } from './index'
import { sql } from 'drizzle-orm'

const EVENTS = [
  { title: 'Absa Cape Epic', slug: 'absa-cape-epic', description: "The world's most prestigious mountain bike stage race — 8 days through the Western Cape mountains.", city: 'Wellington', province: 'Western Cape', venue_name: 'Wellington, Western Cape', address: 'Wellington, Western Cape', event_date_start: '2026-03-22', event_date_end: '2026-03-29', entry_url: 'https://www.cape-epic.com', discipline: 'MTB Stage Race', cover_image_url: '', is_featured: true, status: 'pending_review', entry_status: 'open' },
  { title: 'JoBerg2c', slug: 'joberg2c', description: '9-day MTB stage race from Heidelberg to Scottburgh through the Drakensberg.', city: 'Heidelberg', province: 'Gauteng', venue_name: 'Heidelberg to Scottburgh', address: 'Heidelberg, Gauteng', event_date_start: '2026-04-24', event_date_end: '2026-05-02', entry_url: 'https://www.joberg2c.co.za', discipline: 'MTB Stage Race', cover_image_url: '', is_featured: true, status: 'pending_review', entry_status: 'open' },
  { title: 'Attakwas Extreme', slug: 'attakwas-extreme', description: 'One-day MTB endurance race through the Attakwas mountains — 120km of iconic SA terrain.', city: 'De Rust', province: 'Western Cape', venue_name: 'Oudtshoorn, Western Cape', address: 'Oudtshoorn, Western Cape', event_date_start: '2027-01-30', event_date_end: '2027-01-30', entry_url: 'https://entryninja.com', discipline: 'MTB Endurance', cover_image_url: '', is_featured: false, status: 'pending_review', entry_status: 'open' },
  { title: 'Wines2Whales MTB', slug: 'wines2whales', description: '3-day MTB stage race from the Winelands to the Whale Coast.', city: 'Franschhoek', province: 'Western Cape', venue_name: 'Franschhoek to Hermanus', address: 'Franschhoek, Western Cape', event_date_start: '2026-11-04', event_date_end: '2026-11-06', entry_url: 'https://www.wines2whales.co.za', discipline: 'MTB Stage Race', cover_image_url: '', is_featured: true, status: 'pending_review', entry_status: 'open' },
  { title: 'Tankwa Trek', slug: 'tankwa-trek', description: '4-day MTB stage race through the Tankwa Karoo — the toughest terrain in SA.', city: 'Ceres', province: 'Western Cape', venue_name: 'Tankwa Karoo, Western Cape', address: 'Ceres, Western Cape', event_date_start: '2027-02-04', event_date_end: '2027-02-07', entry_url: 'https://entryninja.com', discipline: 'MTB Stage Race', cover_image_url: '', is_featured: false, status: 'pending_review', entry_status: 'open' },
  { title: 'Cape Pioneer Trek', slug: 'cape-pioneer-trek', description: '7-day MTB stage race through the Cape Overberg and Klein Karoo.', city: 'Mossel Bay', province: 'Western Cape', venue_name: 'Mossel Bay to Swellendam', address: 'Mossel Bay, Western Cape', event_date_start: '2026-10-05', event_date_end: '2026-10-11', entry_url: 'https://www.capepioneertrek.co.za', discipline: 'MTB Stage Race', cover_image_url: '', is_featured: false, status: 'pending_review', entry_status: 'open' },
  { title: 'Sani2C', slug: 'sani2c', description: '3-day MTB race from the Sani Pass to the KZN South Coast.', city: 'Underberg', province: 'KwaZulu-Natal', venue_name: 'Underberg to Scottburgh', address: 'Underberg, KwaZulu-Natal', event_date_start: '2026-05-14', event_date_end: '2026-05-16', entry_url: 'https://www.sani2c.co.za', discipline: 'MTB Stage Race', cover_image_url: '', is_featured: true, status: 'pending_review', entry_status: 'open' },
  { title: 'Cape Town Cycle Tour', slug: 'cape-town-cycle-tour', description: "The world's largest individually timed cycle race — 109km around the Cape Peninsula.", city: 'Cape Town', province: 'Western Cape', venue_name: 'Cape Town', address: 'Cape Town, Western Cape', event_date_start: '2027-03-08', event_date_end: '2027-03-08', entry_url: 'https://www.capetowncycletour.com', discipline: 'Road Race', cover_image_url: '', is_featured: true, status: 'pending_review', entry_status: 'open' },
  { title: '94.7 Cycle Challenge', slug: '947-cycle-challenge', description: '94km road cycle through Johannesburg and surrounds.', city: 'Johannesburg', province: 'Gauteng', venue_name: 'Johannesburg', address: 'Johannesburg, Gauteng', event_date_start: '2026-11-15', event_date_end: '2026-11-15', entry_url: 'https://entryninja.com', discipline: 'Road Race', cover_image_url: '', is_featured: true, status: 'pending_review', entry_status: 'open' },
  { title: 'Amashova Classic', slug: 'amashova-classic', description: '106km road cycle from Pietermaritzburg to Durban through the Valley of a Thousand Hills.', city: 'Pietermaritzburg', province: 'KwaZulu-Natal', venue_name: 'Pietermaritzburg to Durban', address: 'Pietermaritzburg, KwaZulu-Natal', event_date_start: '2026-10-04', event_date_end: '2026-10-04', entry_url: 'https://entryninja.com', discipline: 'Road Race', cover_image_url: '', is_featured: false, status: 'pending_review', entry_status: 'open' },
  { title: 'Berg & Bush MTB', slug: 'berg-and-bush', description: '3-day MTB adventure ride through the Drakensberg foothills.', city: 'Winterton', province: 'KwaZulu-Natal', venue_name: 'Winterton, KwaZulu-Natal', address: 'Winterton, KwaZulu-Natal', event_date_start: '2026-09-18', event_date_end: '2026-09-20', entry_url: 'https://entryninja.com', discipline: 'MTB Stage Race', cover_image_url: '', is_featured: false, status: 'pending_review', entry_status: 'open' },
  { title: 'Karoo to Coast', slug: 'karoo-to-coast', description: 'Epic gravel and MTB adventure from the Karoo to the Eastern Cape coast.', city: 'Graaff-Reinet', province: 'Eastern Cape', venue_name: 'Graaff-Reinet, Eastern Cape', address: 'Graaff-Reinet, Eastern Cape', event_date_start: '2026-08-22', event_date_end: '2026-08-23', entry_url: 'https://entryninja.com', discipline: 'Gravel', cover_image_url: '', is_featured: false, status: 'pending_review', entry_status: 'open' },
  { title: 'Race to the Sun', slug: 'race-to-the-sun', description: '55km road race from Paarl to Hermanus — one of the oldest road races in SA.', city: 'Paarl', province: 'Western Cape', venue_name: 'Paarl to Hermanus', address: 'Paarl, Western Cape', event_date_start: '2027-02-14', event_date_end: '2027-02-14', entry_url: 'https://entryninja.com', discipline: 'Road Race', cover_image_url: '', is_featured: false, status: 'pending_review', entry_status: 'open' },
  { title: 'Gravel & Tar Classic', slug: 'gravel-tar-classic', description: 'Mixed surface gravel-road classic in the Cape Winelands.', city: 'Stellenbosch', province: 'Western Cape', venue_name: 'Stellenbosch', address: 'Stellenbosch, Western Cape', event_date_start: '2026-06-20', event_date_end: '2026-06-20', entry_url: 'https://entryninja.com', discipline: 'Gravel', cover_image_url: '', is_featured: false, status: 'pending_review', entry_status: 'open' },
  { title: 'Rock & Rut MTB Challenge', slug: 'rock-and-rut', description: 'One-day MTB endurance race through the Cradle of Humankind.', city: 'Johannesburg', province: 'Gauteng', venue_name: 'Cradle of Humankind, Gauteng', address: 'Lanseria, Gauteng', event_date_start: '2026-07-25', event_date_end: '2026-07-25', entry_url: 'https://entryninja.com', discipline: 'MTB', cover_image_url: '', is_featured: false, status: 'pending_review', entry_status: 'open' },
]

async function main() {
  console.log(`Seeding ${EVENTS.length} events...`)
  for (const e of EVENTS) {
    await db.execute(sql`
      INSERT INTO events (title, slug, description, city, province, venue_name, address, event_date_start, event_date_end, entry_url, discipline, cover_image_url, is_featured, status, entry_status, country, created_at, updated_at)
      VALUES (${e.title}, ${e.slug}, ${e.description}, ${e.city}, ${e.province}, ${e.venue_name}, ${e.address}, ${e.event_date_start}::date, ${e.event_date_end}::date, ${e.entry_url}, ARRAY[${e.discipline}]::text[], ${e.cover_image_url}, ${e.is_featured}, ${e.status}, ${e.entry_status}, 'South Africa', NOW(), NOW())
      ON CONFLICT (slug) DO NOTHING
    `)
    process.stdout.write('.')
  }
  const [{ count }] = await db.execute(sql`SELECT COUNT(*)::int as count FROM events`) as any
  console.log(`\n✅ Done — ${count} events in DB`)
  process.exit(0)
}
main().catch(e => { console.error(e.message); process.exit(1) })
