import { sql } from "drizzle-orm";
import { db } from "./index";

// Map business types to the actual enum values
// shop, brand, service_center, tour_operator, event_organiser
const businesses = [
  {
    name: "CWCycles",
    slug: "cwcycles",
    business_type: "shop",
    description: "Since 1992, CWCycles has been Cape Town's trusted source for high-quality road and mountain bikes. We stock Trek, Specialized, and Giant bikes with expert fitting services.",
    province: "Western Cape",
    city: "Cape Town",
    address: "123 Main Road, Camps Bay, Cape Town",
    location_lat: -33.9249,
    location_lng: 18.3822,
    phone: "+27 21 438 1234",
    email: "info@cwcycles.co.za",
    website: "https://cwcycles.co.za",
    brands_stocked: '{"Trek","Specialized","Giant"}',
    services: '{"Bike Sales","Repairs","Fitting","Wheel Truing"}',
    is_verified: true,
  },
  {
    name: "CycleLab",
    slug: "cyclelab-jhb",
    business_type: "shop",
    description: "CycleLab operates across three Johannesburg locations, offering comprehensive bike sales, expert repairs, and custom builds. We're the go-to workshop for serious cyclists.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "456 Oxford Road, Illovo, Johannesburg",
    location_lat: -26.1367,
    location_lng: 28.0531,
    phone: "+27 11 880 5678",
    email: "info@cyclelab.co.za",
    website: "https://cyclelab.co.za",
    brands_stocked: '{"Trek","Specialized","Canyon","SRAM"}',
    services: '{"Bike Sales","Workshop","Custom Builds","Repairs"}',
    is_verified: true,
  },
  {
    name: "Pro Bikes",
    slug: "probikes-ct",
    business_type: "shop",
    description: "Premium Specialized & Road Bike Specialists. Pro Bikes specializes in high-end road bikes, triathlon bikes, and premium components. Expert fitters on staff.",
    province: "Western Cape",
    city: "Cape Town",
    address: "789 Long Street, Cape Town",
    location_lat: -33.9216,
    location_lng: 18.4233,
    phone: "+27 21 424 2000",
    email: "sales@probikes.co.za",
    website: "https://probikes.co.za",
    brands_stocked: '{"Specialized","Cervélo","Felt"}',
    services: '{"Bike Fitting","Road Bike Sales","Components"}',
    is_premium: true,
    is_verified: true,
  },
  {
    name: "Pedal Power",
    slug: "pedal-power-ct",
    business_type: "shop",
    description: "Your Neighborhood Bike Shop. Mass market bike shop offering affordable bikes for the whole family, repairs, and accessories.",
    province: "Western Cape",
    city: "Cape Town",
    address: "321 Kloof Nek Road, Camps Bay, Cape Town",
    location_lat: -33.9301,
    location_lng: 18.3842,
    phone: "+27 21 438 5555",
    email: "info@pedalpower.co.za",
    website: "https://pedalpower.co.za",
    brands_stocked: '{"Trek","Giant","Huffy","Schwinn"}',
    services: '{"Bike Sales","Repairs","Accessories"}',
  },
  {
    name: "Cycle Surgeon",
    slug: "cycle-surgeon-ct",
    business_type: "service_center",
    description: "Expert Bike Repair & Maintenance Specialist. Specializing in complex repairs, wheel building, and custom modifications. We handle what others won't.",
    province: "Western Cape",
    city: "Cape Town",
    address: "555 Buitengracht Street, Salt River, Cape Town",
    location_lat: -33.9356,
    location_lng: 18.4486,
    phone: "+27 21 465 1234",
    email: "surgeon@cyclesurgeon.co.za",
    website: "https://cyclesurgeon.co.za",
    brands_stocked: null,
    services: '{"Repairs","Wheel Building","Custom Work","Tuning"}',
  },
  {
    name: "Bikeology",
    slug: "bikeology-ct",
    business_type: "shop",
    description: "High-End Road & Triathlon Specialist. Dedicated to road and triathlon cycling. Premium components, expert advice, and precision fitting.",
    province: "Western Cape",
    city: "Cape Town",
    address: "888 Main Road, Green Point, Cape Town",
    location_lat: -33.9061,
    location_lng: 18.4119,
    phone: "+27 21 433 1111",
    email: "info@bikeology.co.za",
    website: "https://bikeology.co.za",
    brands_stocked: '{"Cervélo","Felt","SRAM","Shimano"}',
    services: '{"Bike Fitting","Road Bikes","Tri Bikes","Components"}',
    is_premium: true,
    is_verified: true,
  },
  {
    name: "Bikestore",
    slug: "bikestore-online",
    business_type: "shop",
    description: "South Africa's Premier Online Cycling Retailer. Full range of bikes, components, and apparel delivered nationwide. Fast shipping, competitive prices.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "999 Commerce Street, Sandton, Johannesburg",
    location_lat: -26.1089,
    location_lng: 28.0644,
    phone: "+27 11 784 5000",
    email: "sales@bikestore.co.za",
    website: "https://bikestore.co.za",
    brands_stocked: '{"Trek","Specialized","Giant","Canyon","Merida"}',
    services: '{"Online Sales","Delivery","Support"}',
    is_verified: true,
  },
  {
    name: "BikesOnline.co.za",
    slug: "bikesonline",
    business_type: "brand",
    description: "Importer & Distributor of Premium Bike Brands. Official importer of leading global bike brands. Supplying retailers and consumers across South Africa.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "111 Industrial Park, Isando, Johannesburg",
    location_lat: -26.1767,
    location_lng: 28.2269,
    phone: "+27 11 613 5555",
    email: "imports@bikesonline.co.za",
    website: "https://bikesonline.co.za",
    brands_stocked: '{"Canyon","Focus","Merida","Ghost"}',
    services: '{"Wholesale","Importation","Distribution"}',
    is_verified: true,
  },
  {
    name: "Sportsman's Warehouse (Cycling)",
    slug: "sportsmans-warehouse-cycling",
    business_type: "shop",
    description: "National Chain with Cycling Excellence. Multi-location sports retailer with dedicated cycling departments nationwide. Quality bikes and expert staff.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "222 Retail Park, Bryanston, Johannesburg",
    location_lat: -26.0669,
    location_lng: 28.0447,
    phone: "+27 11 463 0888",
    email: "cycling@sportsmans.co.za",
    website: "https://sportsmans.co.za",
    brands_stocked: '{"Trek","Specialized","Giant","Huffy"}',
    services: '{"Bike Sales","Repairs","Accessories","Rentals"}',
    is_verified: true,
  },
  {
    name: "Cape Cycle Tours",
    slug: "cape-cycle-tours",
    business_type: "tour_operator",
    description: "Explore Cape Town on Two Wheels. Bike rental and guided tours throughout Cape Town. From casual city rides to challenging mountain routes.",
    province: "Western Cape",
    city: "Cape Town",
    address: "333 Waterfront Drive, V&A Waterfront, Cape Town",
    location_lat: -33.9028,
    location_lng: 18.4219,
    phone: "+27 21 418 5000",
    email: "tours@capecycletours.co.za",
    website: "https://capecycletours.co.za",
    brands_stocked: null,
    services: '{"Bike Rental","Guided Tours","Events"}',
  },
  {
    name: "Dirt & Trail",
    slug: "dirt-trail-jhb",
    business_type: "shop",
    description: "MTB Specialists for Serious Trail Riders. Focused exclusively on mountain bikes. Expert advice, quality hardtails and full-suspension bikes, trail knowledge.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "444 Mountain Avenue, Sunninghill, Johannesburg",
    location_lat: -26.0422,
    location_lng: 28.0381,
    phone: "+27 11 469 5678",
    email: "info@dirttrail.co.za",
    website: "https://dirttrail.co.za",
    brands_stocked: '{"Trek","Specialized","Giant","Kona"}',
    services: '{"MTB Sales","Repairs","Trail Advice","Events"}',
  },
  {
    name: "Cycle Zone",
    slug: "cycle-zone-pretoria",
    business_type: "shop",
    description: "Pretoria's Community Bike Shop. Locally-owned bike shop serving Pretoria cyclists with quality bikes, repairs, and friendly service.",
    province: "Gauteng",
    city: "Pretoria",
    address: "555 Church Street, Pretoria Central, Pretoria",
    location_lat: -25.7482,
    location_lng: 28.2293,
    phone: "+27 12 320 1234",
    email: "info@cyclezone.co.za",
    website: "https://cyclezone.co.za",
    brands_stocked: '{"Trek","Giant","Merida"}',
    services: '{"Bike Sales","Repairs","Accessories"}',
  },
  {
    name: "Bicycle Mechanic",
    slug: "bicycle-mechanic-ct",
    business_type: "service_center",
    description: "Award-Winning Bike Repair & Restoration. Master mechanic with 25+ years experience. Specializing in vintage restoration and precision tuning.",
    province: "Western Cape",
    city: "Cape Town",
    address: "666 Harrington Street, Salt River, Cape Town",
    location_lat: -33.9367,
    location_lng: 18.4498,
    phone: "+27 21 465 5555",
    email: "master@bicyclemechanic.co.za",
    website: "https://bicyclemechanic.co.za",
    brands_stocked: null,
    services: '{"Repairs","Restoration","Tune-ups","Vintage Work"}',
    is_verified: true,
  },
  {
    name: "TriSports",
    slug: "trisports-ct",
    business_type: "shop",
    description: "Triathlon Bikes & Training Specialist. Dedicated to triathlon cycling. Tri-specific bikes, coaching partnerships, and race preparation.",
    province: "Western Cape",
    city: "Cape Town",
    address: "777 Strand Road, Strand, Cape Town",
    location_lat: -34.3469,
    location_lng: 18.8552,
    phone: "+27 21 853 2222",
    email: "info@trisports.co.za",
    website: "https://trisports.co.za",
    brands_stocked: '{"Cervélo","Felt","Trek Madone"}',
    services: '{"Tri Bikes","Bike Fitting","Coaching"}',
  },
  {
    name: "Summit Bikes",
    slug: "summit-bikes-ct",
    business_type: "shop",
    description: "Road Cycling Excellence in Cape Town. Specializing in premium road bikes and gravel bikes. Expert fitters for optimal performance.",
    province: "Western Cape",
    city: "Cape Town",
    address: "888 Victoria Road, Camps Bay, Cape Town",
    location_lat: -33.9268,
    location_lng: 18.3876,
    phone: "+27 21 438 7777",
    email: "info@summitbikes.co.za",
    website: "https://summitbikes.co.za",
    brands_stocked: '{"Specialized","Cervélo","Canyon"}',
    services: '{"Road Bikes","Gravel Bikes","Fitting"}',
    is_premium: true,
  },
  {
    name: "Cycle Hub",
    slug: "cycle-hub-durban",
    business_type: "shop",
    description: "Durban's Bike Shop Destination. Full-service bike shop serving Durban's cycling community with quality bikes and expert repairs.",
    province: "KwaZulu-Natal",
    city: "Durban",
    address: "999 Smith Street, Durban Central, Durban",
    location_lat: -29.8587,
    location_lng: 31.0277,
    phone: "+27 31 201 5678",
    email: "info@cyclehub.co.za",
    website: "https://cyclehub.co.za",
    brands_stocked: '{"Trek","Specialized","Giant"}',
    services: '{"Bike Sales","Repairs","Accessories"}',
  },
  {
    name: "LifeCycle Bicycles",
    slug: "lifecycle-pe",
    business_type: "shop",
    description: "Port Elizabeth's Premier Cycle Retailer. Community-focused bike shop in Port Elizabeth offering quality bikes, expert service, and local knowledge.",
    province: "Eastern Cape",
    city: "Port Elizabeth",
    address: "111 Main Street, Port Elizabeth Central, Port Elizabeth",
    location_lat: -33.9649,
    location_lng: 25.6050,
    phone: "+27 41 585 1234",
    email: "info@lifecycle.co.za",
    website: "https://lifecycle.co.za",
    brands_stocked: '{"Trek","Giant","Merida"}',
    services: '{"Bike Sales","Repairs","Community Events"}',
  },
  {
    name: "Silverback Bikes",
    slug: "silverback-bikes",
    business_type: "brand",
    description: "South African MTB Brand & Importer. Iconic SA mountain bike brand. Manufacturing and importing quality MTBs for African riders.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "222 Industrial Road, Isando, Johannesburg",
    location_lat: -26.1745,
    location_lng: 28.2252,
    phone: "+27 11 609 4545",
    email: "info@silverbackbikes.co.za",
    website: "https://silverbackbikes.co.za",
    brands_stocked: '{"Silverback"}',
    services: '{"Manufacturing","Retail","Distribution"}',
    is_verified: true,
  },
  {
    name: "Pyga Industries",
    slug: "pyga-industries",
    business_type: "brand",
    description: "Premium SA Gravel & Adventure Bikes. South African manufacturer of award-winning gravel and adventure bikes. Handcrafted quality.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "333 Craft Way, Isando, Johannesburg",
    location_lat: -26.1690,
    location_lng: 28.2310,
    phone: "+27 11 615 5555",
    email: "info@pyga.co.za",
    website: "https://pyga.co.za",
    brands_stocked: '{"PYGA"}',
    services: '{"Manufacturing","Custom Builds","Retail"}',
    is_premium: true,
    is_verified: true,
  },
  {
    name: "Momsen Bicycles",
    slug: "momsen-bicycles",
    business_type: "brand",
    description: "South African E-Bike Innovator. Premium e-bike brand from SA. Combining technology with local manufacturing expertise.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "444 Innovation Drive, Sandown, Johannesburg",
    location_lat: -26.1047,
    location_lng: 28.0686,
    phone: "+27 11 784 9999",
    email: "info@momsen.co.za",
    website: "https://momsen.co.za",
    brands_stocked: '{"Momsen"}',
    services: '{"E-Bike Sales","Manufacturing","Support"}',
    is_verified: true,
  },
];

async function seed() {
  try {
    console.log("Starting seed of 20 SA cycling businesses...\n");

    for (const business of businesses) {
      try {
        // Use raw SQL for array insertion
        await db.execute(sql.raw(`
          INSERT INTO businesses (
            name, slug, business_type, description,
            province, city, address, location_lat, location_lng,
            phone, email, website,
            brands_stocked, services,
            is_premium, is_verified
          ) VALUES (
            '${business.name.replace(/'/g, "''")}',
            '${business.slug}',
            '${business.business_type}',
            '${business.description.replace(/'/g, "''")}',
            '${business.province}',
            '${business.city}',
            '${business.address}',
            ${business.location_lat},
            ${business.location_lng},
            '${business.phone}',
            '${business.email}',
            '${business.website}',
            ${business.brands_stocked ? `'${business.brands_stocked}'::text[]` : 'NULL'},
            '${business.services}'::text[],
            ${business.is_premium ? 'true' : 'false'},
            ${business.is_verified ? 'true' : 'false'}
          )
        `));
        console.log(`✓ Seeded: ${business.name} (${business.slug})`);
      } catch (e: any) {
        if (e.message.includes("duplicate key") || e.cause?.code === "23505") {
          console.log(`⚠️  Already exists: ${business.name}`);
        } else {
          console.error(`✗ Error seeding ${business.name}:`, e.message);
          throw e;
        }
      }
    }

    console.log("\n✅ Seed completed successfully!");
    process.exit(0);
  } catch (error) {
    console.error("❌ Seed failed:", error);
    process.exit(1);
  }
}

seed();
