/**
 * SA Bike Brands Knowledge Base
 * Top 80+ brands commonly found in South African cycling market
 */

export const SA_BIKE_BRANDS = [
  // Premium International
  'Trek',
  'Specialized',
  'Giant',
  'Scott',
  'Cannondale',
  'Cervélo',
  'Focus',
  'BMC',
  'Colnago',
  'Pinarello',
  'Felt',
  'Merida',
  'Cube',
  'Ghost',
  'Kona',
  'Commencal',
  'YT Industries',
  'Nukeproof',
  'Canyon',
  'Orbea',

  // Mid-Range International
  'Diamondback',
  'GT',
  'Marin',
  'Salsa Cycles',
  'Surly',
  'Transition',
  'Pivot',
  'Whyte',
  'Vitus',
  'Ragley',
  'Hardtail Heroes',
  'Bombtrack',
  'Charge Bikes',
  'Stanridge',
  'Cotic',
  'Fezzari',

  // Budget/Value
  'Huffy',
  'Mongoose',
  'Schwinn',
  'Decathlon',
  'Carrera',
  'Muddyfox',
  'Boardman',
  'Reflex',
  'Triban',

  // South African / Regional Brands
  'Silverback',
  'Bell Cycles',
  'Kinesis',
  'Thorn',
  'Roberts',
  'BSA',
  'Avanti',
  'Jub-Jub',
  'Optimal',
  'Kootu',
  'Storm Bikes',
  'Allo Bikes',
  'Mongoose SA',
  'MUSA',

  // E-Bike Specialist
  'Riese & Müller',
  'Stromer',
  'Gazelle',
  'Coboc',
  'BH EasyMotion',
  'Trek Rail',
  'Specialized Turbo',

  // Component/Part Brands (relevant for parts listings)
  'Shimano',
  'SRAM',
  'Campagnolo',
  'Oneup',
  'Race Face',
  'Deity',
  'Hope',
  'Magura',
  'Fox',
  'RockShox',
  'DT Swiss',
  'Mavic',
  'Fulcrum',
  'Continental',
  'Schwalbe',
  'Michelin',
  'Vittoria',
  'Maxxis',
  'Kenda',
  'Pirelli',
  'Pirelli Scorpion',
]
