import { neon } from '@neondatabase/serverless';
const sql = neon(process.env.DATABASE_URL!);

const events = [
  // ── WESTERN CAPE (missing) ──────────────────────────────────────────────────
  { title:'Attakwas Extreme — Half', slug:'attakwas-half-2026', type:'race', city:'Oudtshoorn', province:'Western Cape', venue:'Chandelier Game Reserve', start:'2026-01-17', end:'2026-01-17', entry:'https://dryland.co.za/attakwas-extreme/', organiser:'Dryland Event Management', org_web:'https://dryland.co.za', distance:'47km / 115km / 155km', desc:'The half and gravel distance versions of the iconic Attakwas Extreme — South Africa\'s Hell of the South. Starting from Chandelier Game Reserve near Oudtshoorn with 47km, 115km and 155km gravel options. E-bikes welcome. Dryland\'s flagship January event in the Klein Karoo. January 17, 2026.' },
  { title:'99er Cycle Tour', slug:'99er-cycle-tour-2026', type:'race', city:'Durbanville', province:'Western Cape', venue:'Durbanville Sports Grounds', start:'2026-02-07', end:'2026-02-07', entry:'https://99er.co.za', organiser:'99er Cycle Tour', org_web:'https://99er.co.za', distance:'45km / 76km / 80km / 95km', desc:'A Western Cape classic — the 99er Cycle Tour through the scenic Durbanville wine valleys. Four distances from 45km to 95km with an official cycling SA seeding event. Gravel and MTB options available. Held at Durbanville Sports Grounds. February 7, 2026.' },
  { title:'Leopard Crawl MTB', slug:'leopard-crawl-mtb-2026', type:'race', city:'Oudtshoorn', province:'Western Cape', venue:'Wesbank Primary School, Oudtshoorn', start:'2026-02-14', end:'2026-02-14', entry:'https://www.racespace.co.za/race/5472-leopard-crawl-mtb-and-trail', organiser:'Leopard Crawl Events', org_web:'https://events.myactive.co.za', distance:'13km / 18km / 45km / 72km', desc:'Annual MTB and trail event in Oudtshoorn, Klein Karoo. Four distances from 13km to 72km through the rugged Oudtshoorn terrain. Valentine\'s weekend event with great community atmosphere. February 14, 2026.' },
  { title:'Oak Valley 24 Hour', slug:'oak-valley-24hr-2026', type:'race', city:'Grabouw', province:'Western Cape', venue:'Oak Valley Wine Estate, Elgin', start:'2026-03-28', end:'2026-03-29', entry:'https://www.racespace.co.za/race/5040-the-oak-valley-24-hour', organiser:'Oak Valley Events', org_web:'https://www.oakvalley.co.za', distance:'5km / 12km loops (24hr)', desc:'Annual 24-hour MTB and trail running event at the stunning Oak Valley Wine Estate near Grabouw. Riders tackle as many laps as possible through the night across Elgin Valley wine farm terrain. Family-friendly atmosphere. March 28–29, 2026.' },
  { title:'Windpomp XCM — Stilbaai', slug:'windpomp-xcm-stilbaai-2026', type:'race', city:'Stilbaai', province:'Western Cape', venue:'The Stables, Stilbaai', start:'2026-04-04', end:'2026-04-04', entry:'https://www.racespace.co.za/race/6487-windpomp-xcm-60km-stilbaai', organiser:'Windpomp Events', org_web:'https://events.myactive.co.za', distance:'14km / 28km / 60km', desc:'Annual MTB challenge at The Stables in Stilbaai along the Garden Route coast. Three distances: 14km, 28km and 60km through the beautiful Agulhas region. Community event with a great coastal atmosphere. April 4, 2026.' },
  { title:'The Greyt Onion', slug:'greyt-onion-2026', type:'race', city:'Genadendal', province:'Western Cape', venue:'Middelplaas Farm, Genadendal', start:'2026-04-18', end:'2026-04-18', entry:'https://www.racespace.co.za/race/6390-the-greyt-onion', organiser:'Greyt Onion Events', org_web:'https://events.myactive.co.za', distance:'40km / 60km', desc:'Annual MTB race at Middelplaas Farm near Genadendal in the Overberg. Two distances: 40km and 60km through scenic Overberg farmlands and mountain passes. Great community event in the Theewaterskloof area. April 18, 2026.' },
  { title:'Weekend Warrior Grabouw', slug:'weekend-warrior-grabouw-2026', type:'stage_race', city:'Grabouw', province:'Western Cape', venue:'Elgin Grabouw Country Club', start:'2026-04-18', end:'2026-04-19', entry:'https://redcherryevents.co.za', organiser:'Red Cherry Events', org_web:'https://redcherryevents.co.za', distance:'22km / 40km / 43km / 52km / 85km', desc:'Red Cherry Events\' Weekend Warrior 2-day MTB stage race in Grabouw. Based at Elgin Grabouw Country Club with routes through the Elgin Valley fruit farms and mountains. Five distances from 22km to 85km. Family-friendly, great value stage race experience. April 18–19, 2026.' },
  { title:'Redstone MTB & Trail Challenge', slug:'redstone-mtb-2026', type:'race', city:'Calitzdorp', province:'Western Cape', venue:'Redstone Hills Holiday Farm', start:'2026-05-02', end:'2026-05-02', entry:'https://www.racespace.co.za/race/6411-redstone-mtb-tr-challenge', organiser:'Redstone Events', org_web:'https://events.myactive.co.za', distance:'5km / 18km / 43km / 62km', desc:'Annual MTB and trail run at Redstone Hills Holiday Farm in Calitzdorp, Klein Karoo. Four distances from 5km to 62km through the spectacular red rock terrain of the Klein Karoo valley. E-bikes welcome. May 2, 2026.' },
  { title:'Meiringspoort MTB & Trail', slug:'meiringspoort-mtb-2026', type:'race', city:'De Rust', province:'Western Cape', venue:'De Rust, Meiringspoort', start:'2026-05-16', end:'2026-05-16', entry:'https://www.racespace.co.za/race/6421-meiringspoort-mtb-trail-run-challenge', organiser:'Meiringspoort Events', org_web:'https://events.myactive.co.za', distance:'9.5km / 19.5km / 26km / 41.5km / 61km', desc:'Annual MTB and trail run in the dramatic Meiringspoort Pass near De Rust. Routes tackle the spectacular sandstone gorge and surrounding mountain terrain. Five distances from 9.5km to 61km. One of the Klein Karoo\'s most scenic event venues. May 16, 2026.' },
  { title:'Dibiki MTB & Trail Run', slug:'dibiki-mtb-2026', type:'race', city:'Riversdale', province:'Western Cape', venue:'Riversdale', start:'2026-06-20', end:'2026-06-20', entry:'https://www.racespace.co.za/race/6432-dibiki-mtb-trail-run-challenge', organiser:'Dibiki Events', org_web:'https://events.myactive.co.za', distance:'5km / 17km / 44km / 53km', desc:'Annual MTB and trail run in Riversdale, Garden Route. Four distances from 5km to 53km. Community event in the scenic Riversdale area between Swellendam and Mossel Bay. E-bikes welcome. June 20, 2026.' },
  { title:'The Exploration Challenge — West Coast', slug:'exploration-challenge-2026', type:'race', city:'Langebaan', province:'Western Cape', venue:'West Coast National Park', start:'2026-07-18', end:'2026-07-18', entry:'https://www.racespace.co.za/race/6440-the-exploration-challenge', organiser:'Exploration Events', org_web:'https://events.myactive.co.za', distance:'20km / 50km', desc:'Annual MTB and trail event at the beautiful West Coast National Park in Langebaan. Two distances: 20km and 50km through the unique fynbos coastal terrain of the West Coast. Iconic setting with lagoon views. July 18, 2026.' },
  { title:'Zwartberg Trapsuutjies', slug:'zwartberg-trapsuutjies-2026', type:'race', city:'Prince Albert', province:'Western Cape', venue:'Prince Albert', start:'2026-08-08', end:'2026-08-08', entry:'https://www.racespace.co.za/race/6448-zwartberg-trapsuutjies-fietsren-hardlooproete', organiser:'Prince Albert Events', org_web:'https://events.myactive.co.za', distance:'4km / 12km / 19km / 42km / 63km', desc:'Annual MTB and trail event in the charming Karoo village of Prince Albert at the foot of the Zwartberg mountains. Five distances from 4km to 63km. E-bikes welcome. Spectacular Zwartberg Pass terrain. August 8, 2026.' },
  { title:'Road to Desolation', slug:'road-to-desolation-2026', type:'race', city:'Graaff-Reinet', province:'Western Cape', venue:'Graaff-Reinet', start:'2026-09-26', end:'2026-09-26', entry:'https://www.racespace.co.za/race/5621-road-to-desolation-the-road-to-desolation', organiser:'Road to Desolation Events', org_web:'https://events.myactive.co.za', distance:'66km / 130km / 180km / 626km / 1237km', desc:'Epic gravel and MTB event centred on Graaff-Reinet and the Valley of Desolation. Multiple formats from a 66km Taste to a staggering 1,237km ultra. Set in the hauntingly beautiful Karoo with the Valley of Desolation as centrepiece. September 26, 2026.' },
  { title:'7Weekspoort MTB Challenge', slug:'7weekspoort-mtb-2026', type:'race', city:'Ladismith', province:'Western Cape', venue:'Zoar, Ladismith', start:'2026-10-03', end:'2026-10-03', entry:'https://www.racespace.co.za/race/6369-7weekspoort-mtb-and-trail-run-challenge', organiser:'7Weekspoort Events', org_web:'https://events.myactive.co.za', distance:'5km / 10km / 21km / 29km / 43km / 85km', desc:'Annual MTB and trail run in the spectacular 7Weekspoort valley near Ladismith, Klein Karoo. Six distances from 5km to 85km through dramatic mountain passes and Karoo landscapes. One of the Western Cape\'s most scenic MTB venues. October 3, 2026.' },
  { title:'Ride The Cape Tulbagh', slug:'ride-the-cape-tulbagh-2026', type:'stage_race', city:'Tulbagh', province:'Western Cape', venue:'Tulbagh', start:'2026-10-09', end:'2026-10-09', entry:'https://www.racespace.co.za/race/6462-ride-the-cape-tulbagh', organiser:'Ride The Cape', org_web:'https://events.myactive.co.za', distance:'115km', desc:'Premium 115km MTB experience through the beautiful Tulbagh valley and surrounding mountains. Part of the Ride The Cape series exploring iconic Western Cape wine country terrain. October 9, 2026.' },
  { title:'Prince George', slug:'prince-george-2026', type:'race', city:'Oudtshoorn', province:'Western Cape', venue:'Prince Albert / Oudtshoorn', start:'2026-10-17', end:'2026-10-17', entry:'https://dryland.co.za', organiser:'Dryland Event Management', org_web:'https://dryland.co.za', distance:'73km / 167km', desc:'Dryland\'s premium 100 Miler event — Prince George. Set in the spectacular Klein Karoo between Prince Albert and Oudtshoorn. The 100 Miler (167km) and 50 Miler (73km) options tackle the Swartberg foothills and Karoo plains. One of Dryland\'s finest event offerings. October 17, 2026.' },
  { title:'Ride The Cape Elgin', slug:'ride-the-cape-elgin-2026', type:'stage_race', city:'Elgin', province:'Western Cape', venue:'CherryGlamping Elgin', start:'2026-11-20', end:'2026-11-20', entry:'https://www.racespace.co.za/race/6473-ride-the-cape-elgin', organiser:'Ride The Cape', org_web:'https://events.myactive.co.za', distance:'116km', desc:'116km MTB experience through the stunning Elgin Valley apple and pear orchards near Hermanus. Part of the Ride The Cape series. Premium scenic route through one of the Cape\'s most beautiful agricultural valleys. November 20, 2026.' },
  { title:'Bergplaas Challenge', slug:'bergplaas-challenge-2026', type:'race', city:'Wilderness', province:'Western Cape', venue:'Libertas Guest Farm, Hoekwil', start:'2026-11-28', end:'2026-11-28', entry:'https://www.racespace.co.za/race/6131-bergplaas-challenge', organiser:'Bergplaas Events', org_web:'https://events.myactive.co.za', distance:'7km / 10km / 15km / 28km / 40km / 70km', desc:'Annual MTB and trail event at Libertas Guest Farm near Hoekwil, Wilderness. Six distances from 7km to 70km through the Garden Route forest trails near the Wilderness lakes. Great end-of-year community event. November 28, 2026.' },
  { title:'Monties MTB & Trail Run', slug:'monties-mtb-2026', type:'race', city:'Mossel Bay', province:'Western Cape', venue:'Hartenbos, Mossel Bay', start:'2026-12-26', end:'2026-12-26', entry:'https://www.racespace.co.za/race/6474-monties-cycles-mtb-trail-run-challenge', organiser:'Monties Cycles', org_web:'https://events.myactive.co.za', distance:'6km / 12km / 22km / 41km / 87km', desc:'The Monties MTB & Trail Run Challenge in Hartenbos near Mossel Bay. Five distances from 6km to 87km. Boxing Day event on December 26. E-bikes and gravel bikes welcome. Great holiday atmosphere on the Garden Route. December 26, 2026.' },

  // ── KZN (missing) ──────────────────────────────────────────────────────────
  { title:'Wartburg Classic MTB', slug:'wartburg-classic-2026', type:'race', city:'Wartburg', province:'KwaZulu-Natal', venue:'Fountain Hill Rd, Wartburg', start:'2026-02-21', end:'2026-02-21', entry:'https://www.racespace.co.za/race/6122-wartburg-classic-mtb-60km', organiser:'Wartburg Classic Events', org_web:'https://events.myactive.co.za', distance:'10km / 25km / 45km / 60km', desc:'The beloved Wartburg Classic MTB in the KZN Midlands. Four distances from 10km to 60km through the rolling Midlands farmlands near Wartburg. Community event with multisport options combining trail running and MTB. February 21, 2026.' },
  { title:'The Cane Challenger', slug:'cane-challenger-2026', type:'race', city:'Durban', province:'KwaZulu-Natal', venue:'Cornubia Mall, Cycle Lab', start:'2026-04-12', end:'2026-04-12', entry:'https://www.racespace.co.za/race/6413-the-cane-challenger', organiser:'Cane Challenger Events', org_web:'https://events.myactive.co.za', distance:'9km / 15km / 20km / 40km / 60km', desc:'Annual MTB and trail event in the Cornubia area of Durban North. Five distances from 9km to 60km through the sugarcane fields and coastal forest trails of the KZN North Coast. April 12, 2026.' },
  { title:'New Hanover MTB', slug:'new-hanover-mtb-2026', type:'race', city:'New Hanover', province:'KwaZulu-Natal', venue:'Dalton Rd, New Hanover', start:'2026-05-02', end:'2026-05-02', entry:'https://www.racespace.co.za/race/6493-new-hanover-mtb', organiser:'New Hanover Events', org_web:'https://events.myactive.co.za', distance:'10km / 25km / 45km / 60km', desc:'Annual MTB event in the beautiful New Hanover area of the KZN Midlands. Four distances from 10km to 60km through rolling Midlands dairy and timber farmlands. Great community atmosphere. May 2, 2026.' },
  { title:'Mtunzini Race in the Shade', slug:'mtunzini-race-in-the-shade-2026', type:'race', city:'Mtunzini', province:'KwaZulu-Natal', venue:'Mtunzini', start:'2026-05-17', end:'2026-05-17', entry:'https://www.racespace.co.za/race/6497-mtunzini-race-in-the-shade', organiser:'Mtunzini Events', org_web:'https://events.myactive.co.za', distance:'10km / 25km / 50km / 75km', desc:'Annual MTB race in the shady forests of Mtunzini on the KZN North Coast. Four distances from 10km to 75km through the coastal dune forests and Umlalazi Nature Reserve. One of KZN\'s most beloved forest MTB events. May 17, 2026.' },
  { title:'KAP sani2c Nonstop', slug:'kap-sani2c-nonstop-2026', type:'race', city:'Underberg', province:'KwaZulu-Natal', venue:'Glencairn Farm, Underberg', start:'2026-05-30', end:'2026-05-30', entry:'https://sani2c.co.za', organiser:'KAP sani2c', org_web:'https://sani2c.co.za', distance:'250km nonstop', desc:'The KAP sani2c Nonstop — 250km from Underberg to the Indian Ocean coast without stopping. For riders who find 3 days too relaxing. Self-navigated, solo, brutal — and unforgettable. May 30, 2026.' },
  { title:'KZN Mountain Biking XCO Series', slug:'kzn-xco-series-2026', type:'race', city:'Pietermaritzburg', province:'KwaZulu-Natal', venue:'Cascades, Pietermaritzburg', start:'2026-06-21', end:'2026-06-21', entry:'https://www.racespace.co.za/race/6436-kzn-mountain-biking-xco4', organiser:'KZN Mountain Biking', org_web:'https://www.cyclingsa.com', distance:'20km XCO', desc:'KZN Provincial XCO Mountain Biking Cup series round at Chase Valley, Pietermaritzburg. UCI cross-country format racing for all age categories on a technical XCO course. Part of the KZN provincial series. June 21, 2026.' },
];

async function main() {
  let added = 0, skipped = 0;
  for (const e of events) {
    const exists = await sql`SELECT id FROM events WHERE slug = ${e.slug}`;
    if (exists.length) { console.log('SKIP:', e.title); skipped++; continue; }
    const cover = `https://crankmart.com/uploads/events/${e.slug}.jpg?v=20260330`;
    await sql`
      INSERT INTO events (title, slug, description, event_type, city, province, venue_name,
        event_date_start, event_date_end, entry_url, entry_status, organiser_name, organiser_website,
        discipline, distance, is_featured, cover_image_url, status, country, created_at, updated_at)
      VALUES (${e.title}, ${e.slug}, ${e.desc}, ${e.type}::event_type,
        ${e.city}, ${e.province}, ${e.venue}, ${e.start}::date, ${e.end}::date,
        ${e.entry}, 'open', ${e.organiser}, ${e.org_web},
        ARRAY[${e.title}], ${e.distance}, false, ${cover}, 'pending_review', 'ZA', NOW(), NOW())
    `;
    console.log('ADDED:', e.province.substring(0,2), '|', e.title, '|', e.start);
    added++;
  }
  console.log(`\nDone: ${added} added, ${skipped} skipped`);
  const byProv = await sql`SELECT province, COUNT(*) as c FROM events WHERE status='pending_review' GROUP BY province ORDER BY c DESC` as any[];
  console.log('\nFull calendar:');
  byProv.forEach((r: any) => console.log(`  ${r.province || 'unset'}: ${r.c}`));
}
main().catch(console.error);
