/**
 * CrankMart Business Directory — 80-Listing Seed
 * Generated: 2026-03-29 | Elon (CTO)
 *
 * All listings seeded with:
 *   is_verified: false — unverified until business claims & approves
 *   is_premium:  false — free tier until upgrade
 *
 * business_type enum values: shop | brand | service_center | tour_operator | event_organiser
 *
 * Run: npx tsx src/db/seed-directory-80.ts
 */

import { neon } from "@neondatabase/serverless";

const sql = neon(process.env.DATABASE_URL!);

// ─── Business type mapping ─────────────────────────────────────────────────
// bike_shop       → shop
// online_retailer → shop
// brand_importer  → brand
// mechanic / coach→ service_center
// event_organiser → event_organiser
// bike_hire       → tour_operator

interface Business {
  name: string;
  slug: string;
  business_type: "shop" | "brand" | "service_center" | "tour_operator" | "event_organiser";
  description: string;
  province: string;
  city: string;
  address: string;
  location_lat: number;
  location_lng: number;
  phone: string;
  email: string;
  website: string;
  brands_stocked: string[];
  services: string[];
}

const businesses: Business[] = [

  // ─── BIKE SHOPS — WESTERN CAPE ──────────────────────────────────────────
  {
    name: "CWC Cycles",
    slug: "cwc-cycles-cape-town",
    business_type: "shop",
    description: "One of Cape Town's premier online and in-store cycling retailers. Wide range of road, mountain, gravel and kids bikes with countrywide delivery. Known for competitive pricing and a comprehensive accessory range.",
    province: "Western Cape",
    city: "Cape Town",
    address: "Cape Town, Western Cape",
    location_lat: -33.9249,
    location_lng: 18.4241,
    phone: "",
    email: "info@cwcycles.co.za",
    website: "https://cwcycles.co.za",
    brands_stocked: ["Trek", "Specialized", "Giant"],
    services: ["Bike Sales", "Repairs", "Online Orders", "Accessories"],
  },
  {
    name: "Cycle Lab Cape Town",
    slug: "cycle-lab-cape-town",
    business_type: "shop",
    description: "Leading South African cycling chain with premium technical builds, Retül bike fitting, and a massive accessory range. Carries Specialized, Scott, and Cannondale. Cape Town's most comprehensive cycling store.",
    province: "Western Cape",
    city: "Cape Town",
    address: "Cape Town, Western Cape",
    location_lat: -33.9566,
    location_lng: 18.4681,
    phone: "021 683 8080",
    email: "info@cyclelab.com",
    website: "https://www.cyclelab.com",
    brands_stocked: ["Specialized", "Scott", "Cannondale", "Merida"],
    services: ["Bike Sales", "Repairs", "Bike Fitting", "Online Orders"],
  },
  {
    name: "Gear Change Bicycle Store",
    slug: "gear-change-cape-town",
    business_type: "shop",
    description: "Cape Town's premium Trek dealer and bike fitting specialist. Two stores: Gardens and Tokai. Best-in-class Retül bike fit. Also offers bike hire for visitors and tourists.",
    province: "Western Cape",
    city: "Cape Town",
    address: "Cape Town — Gardens & Tokai locations, Western Cape",
    location_lat: -33.9355,
    location_lng: 18.4170,
    phone: "",
    email: "",
    website: "https://gearchange.co.za",
    brands_stocked: ["Trek", "Bontrager"],
    services: ["Bike Sales", "Bike Fitting", "Repairs", "Bike Hire"],
  },
  {
    name: "East City Cycles",
    slug: "east-city-cycles-cape-town",
    business_type: "shop",
    description: "Independent cycle shop in the Cape Town city bowl. Known for urban, gravel and commuter bikes. Friendly neighbourhood feel with expert mechanic service on Harrington Street.",
    province: "Western Cape",
    city: "Cape Town",
    address: "50 Harrington Street, Shop 5, The Harrington, Cape Town, 8001",
    location_lat: -33.9285,
    location_lng: 18.4286,
    phone: "021 426 6000",
    email: "info@eastcitycycles.com",
    website: "https://eastcitycycles.com",
    brands_stocked: [],
    services: ["Bike Sales", "Repairs", "Accessories"],
  },
  {
    name: "JOC Cycles",
    slug: "joc-cycles-cape-town",
    business_type: "shop",
    description: "Premium cycling retailer in Cape Town's Green Point, stocking high-end road and MTB bikes, components, and apparel. Focused on quality brands and expert service for serious riders.",
    province: "Western Cape",
    city: "Cape Town",
    address: "Cape Town, 8005, Western Cape",
    location_lat: -33.9086,
    location_lng: 18.4112,
    phone: "+27 21 434 7741",
    email: "john@joccycles.co.za",
    website: "https://www.joccycles.co.za",
    brands_stocked: [],
    services: ["Bike Sales", "Repairs", "Accessories"],
  },
  {
    name: "Freewheel Cycles",
    slug: "freewheel-cycles-cape-town",
    business_type: "shop",
    description: "High-end Specialized concept store and service centre in Cape Town. Renowned for premium S-Works builds, Retül bike fitting, and expert technical service. Book a fit by appointment.",
    province: "Western Cape",
    city: "Cape Town",
    address: "Cape Town, Western Cape",
    location_lat: -33.9320,
    location_lng: 18.5006,
    phone: "",
    email: "dan@freewheel.co.za",
    website: "https://freewheel.co.za",
    brands_stocked: ["Specialized", "Roval"],
    services: ["Bike Sales", "Bike Fitting", "Repairs"],
  },
  {
    name: "Olympic Cycles",
    slug: "olympic-cycles-cape-town",
    business_type: "shop",
    description: "Well-established Cape Town bike shop offering sales, repairs, bike fitting and bike hire. Great range of road and commuter bikes. Rent by the day — ideal for visitors.",
    province: "Western Cape",
    city: "Cape Town",
    address: "Cape Town, Western Cape",
    location_lat: -33.9249,
    location_lng: 18.4241,
    phone: "",
    email: "",
    website: "https://www.olympiccycles.co.za",
    brands_stocked: [],
    services: ["Bike Sales", "Repairs", "Bike Fitting", "Bike Hire"],
  },
  {
    name: "Pro Bikes Cape Town",
    slug: "pro-bikes-cape-town",
    business_type: "shop",
    description: "Multi-location Cape Town cycling store known for race support, competitive pricing, and a wide range of road, MTB and gravel bikes. Popular with racing cyclists and club riders.",
    province: "Western Cape",
    city: "Cape Town",
    address: "Cape Town, Western Cape",
    location_lat: -33.9249,
    location_lng: 18.4241,
    phone: "",
    email: "",
    website: "https://probikes.co.za",
    brands_stocked: [],
    services: ["Bike Sales", "Repairs", "Race Support", "Accessories"],
  },
  {
    name: "Specialized Bicycles Africa",
    slug: "specialized-bicycles-africa",
    business_type: "brand",
    description: "Official Specialized Bicycle Components distributor and concept store for Southern Africa. Full range from entry-level to S-Works. Extensive dealer network across South Africa.",
    province: "Western Cape",
    city: "Cape Town",
    address: "Cape Town, Western Cape",
    location_lat: -33.9249,
    location_lng: 18.4241,
    phone: "",
    email: "",
    website: "https://specializedbicyclesafrica.com",
    brands_stocked: ["Specialized", "Roval"],
    services: ["Distribution", "Retail", "Brand Support"],
  },

  // ─── BIKE HIRE — WESTERN CAPE ────────────────────────────────────────────
  {
    name: "Gravel & Tar",
    slug: "gravel-tar-cape-town",
    business_type: "tour_operator",
    description: "Premium bicycle rental company in Cape Town's Southern Suburbs. Specialises in Specialized road, gravel, and mountain bikes for tourists and visiting cyclists. Flexible hire periods.",
    province: "Western Cape",
    city: "Cape Town",
    address: "Cape Town Southern Suburbs, Western Cape",
    location_lat: -34.0085,
    location_lng: 18.4682,
    phone: "",
    email: "",
    website: "https://www.gravel-tar.co.za",
    brands_stocked: ["Specialized"],
    services: ["Bike Hire", "Road Bikes", "Gravel Bikes", "MTB Hire"],
  },
  {
    name: "iRide Africa",
    slug: "iride-africa-cape-town",
    business_type: "tour_operator",
    description: "Cape Town's go-to bike rental for road, gravel, and mountain bikes. Extensive range of quality bikes with flexible hire periods. Serves tourists, corporate groups, and visiting cyclists.",
    province: "Western Cape",
    city: "Cape Town",
    address: "Cape Town, Western Cape",
    location_lat: -33.9249,
    location_lng: 18.4241,
    phone: "",
    email: "",
    website: "https://www.irideafrica.com",
    brands_stocked: [],
    services: ["Bike Hire", "Road Bikes", "Gravel Bikes", "MTB Hire"],
  },
  {
    name: "UP Cycles",
    slug: "upcycles-cape-town",
    business_type: "tour_operator",
    description: "Cape Town adventure tour and bike rental company. Guided cycling tours through the Cape Peninsula. Ideal for tourists looking to experience Cape Town on two wheels.",
    province: "Western Cape",
    city: "Cape Town",
    address: "Cape Town, Western Cape",
    location_lat: -33.9249,
    location_lng: 18.4241,
    phone: "",
    email: "",
    website: "https://upcycles.co.za",
    brands_stocked: [],
    services: ["Bike Hire", "Guided Tours", "City Tours"],
  },
  {
    name: "Bicycle Hire Cape Town",
    slug: "bicycle-hire-cape-town",
    business_type: "tour_operator",
    description: "Affordable bicycle rentals in Cape Town. Alloy road bikes and cruiser bikes from R190/day. Wide selection for tourists, commuters, and visitors to Cape Town.",
    province: "Western Cape",
    city: "Cape Town",
    address: "Cape Town, Western Cape",
    location_lat: -33.9249,
    location_lng: 18.4241,
    phone: "",
    email: "",
    website: "https://bicyclehire.co.za",
    brands_stocked: [],
    services: ["Bike Hire", "Road Bikes", "Cruiser Bikes"],
  },
  {
    name: "Bike Park at Uitsig",
    slug: "bike-park-uitsig-cape-town",
    business_type: "tour_operator",
    description: "Mountain bike hire in the Constantia Valley from R50–R120/hour. Bikes plus protection gear available. Ideal for families and beginners on the scenic Uitsig trails.",
    province: "Western Cape",
    city: "Cape Town",
    address: "Constantia Valley, Cape Town, Western Cape",
    location_lat: -34.0175,
    location_lng: 18.4349,
    phone: "",
    email: "",
    website: "https://bikeparkatuitsig.co.za",
    brands_stocked: [],
    services: ["MTB Hire", "Family Rides", "Trail Access"],
  },

  // ─── WORKSHOP / FITTING — WESTERN CAPE ──────────────────────────────────
  {
    name: "Canyon Café Workshop",
    slug: "canyon-cafe-workshop-cape-town",
    business_type: "service_center",
    description: "Quality workshop service in Cape Town with transparent pricing. Minor service R500, major service R850, hourly labour R500. Professional mechanics with fast 24–48hr turnaround.",
    province: "Western Cape",
    city: "Cape Town",
    address: "Cape Town, Western Cape",
    location_lat: -33.9249,
    location_lng: 18.4241,
    phone: "",
    email: "",
    website: "https://canyoncafe.co.za",
    brands_stocked: [],
    services: ["Repairs", "Servicing", "Custom Builds"],
  },
  {
    name: "SSISA Bike Fitting",
    slug: "ssisa-bike-fitting-cape-town",
    business_type: "service_center",
    description: "Professional bike fitting at the Sports Science Institute of SA in Newlands. Basic to professional fitting packages, plus Fatmax, VO2 max and lactate testing. World-class sports science expertise.",
    province: "Western Cape",
    city: "Cape Town",
    address: "Sports Science Institute of SA, Boundary Road, Newlands, Cape Town",
    location_lat: -33.9840,
    location_lng: 18.4713,
    phone: "",
    email: "",
    website: "https://www.ssisa.com/sports-performance/cycling",
    brands_stocked: [],
    services: ["Bike Fitting", "VO2 Max Testing", "Performance Testing"],
  },
  {
    name: "Daisyway Coaching Systems",
    slug: "daisyway-coaching",
    business_type: "service_center",
    description: "Expert cycling coaching in South Africa with custom training plans, professional bike fit, skills coaching and training camps. Proven methodology for endurance and performance improvement.",
    province: "Western Cape",
    city: "Cape Town",
    address: "Cape Town, Western Cape",
    location_lat: -33.9249,
    location_lng: 18.4241,
    phone: "",
    email: "",
    website: "https://www.daisyway.co.za",
    brands_stocked: [],
    services: ["Cycling Coaching", "Bike Fitting", "Training Plans", "Training Camps"],
  },
  {
    name: "Science to Sport Coaching",
    slug: "science-to-sport-coaching",
    business_type: "service_center",
    description: "Evidence-based cycling coaching from certified coaches. ErgoFit bike fitting. Structured training programs for amateur and elite cyclists. Based at Sports Science Institute, Cape Town.",
    province: "Western Cape",
    city: "Cape Town",
    address: "Cape Town, Western Cape",
    location_lat: -33.9249,
    location_lng: 18.4241,
    phone: "",
    email: "",
    website: "https://www.sciencetosport.com/coaching/",
    brands_stocked: [],
    services: ["Cycling Coaching", "Bike Fitting", "Performance Testing"],
  },

  // ─── BIKE SHOPS — GAUTENG (JHB) ─────────────────────────────────────────
  {
    name: "Cycle Lab Fourways",
    slug: "cycle-lab-fourways",
    business_type: "shop",
    description: "One of South Africa's flagship cycling superstores. Massive showroom in Fourways with road, MTB, gravel, kids and e-bikes. Expert workshop, Retül fitting studio, and a huge apparel range.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "Unit 1, Fourways, Johannesburg, Gauteng",
    location_lat: -26.0309,
    location_lng: 28.0070,
    phone: "011 707 4700",
    email: "info@cyclelab.com",
    website: "https://www.cyclelab.com",
    brands_stocked: ["Specialized", "Scott", "Cannondale", "Merida"],
    services: ["Bike Sales", "Repairs", "Bike Fitting", "Online Orders"],
  },
  {
    name: "Ridgeway Cycles",
    slug: "ridgeway-cycles-johannesburg",
    business_type: "shop",
    description: "Johannesburg online and in-store bike shop with a wide range of bicycles, gear and accessories. Competitive pricing and expert advice. Countrywide delivery available.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "Johannesburg South, Gauteng",
    location_lat: -26.2762,
    location_lng: 28.0138,
    phone: "",
    email: "",
    website: "https://ridgewaycycles.co.za",
    brands_stocked: [],
    services: ["Bike Sales", "Repairs", "Online Orders"],
  },
  {
    name: "Solomons Cycles",
    slug: "solomons-cycles-johannesburg",
    business_type: "shop",
    description: "Full-service cycling store in Johannesburg with a wide selection of bikes, gear, and accessories. Known for expert service and great deals both online and in-store.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "Johannesburg, Gauteng",
    location_lat: -26.2041,
    location_lng: 28.0473,
    phone: "",
    email: "",
    website: "https://solomonscycles.co.za",
    brands_stocked: [],
    services: ["Bike Sales", "Repairs", "Accessories"],
  },
  {
    name: "Mellow Velo Cycles",
    slug: "mellow-velo-fourways",
    business_type: "shop",
    description: "Full-service cycle shop at Broadacres Shopping Centre, Fourways. Stocks Titan Racing, Muna kids bikes, and a curated range of road and gravel bikes. Mission: awesome retail and riding experience.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "7 Broadacres Shopping Centre, Cedar Road, Fourways, Johannesburg",
    location_lat: -26.0261,
    location_lng: 28.0008,
    phone: "",
    email: "",
    website: "https://mellowvelo.co.za",
    brands_stocked: ["Titan Racing", "Muna"],
    services: ["Bike Sales", "Repairs", "Accessories"],
  },
  {
    name: "Linden Cycles",
    slug: "linden-cycles-johannesburg",
    business_type: "shop",
    description: "Neighbourhood bike shop in Linden, Johannesburg. Specialises in MTB, commuter bikes and accessories. Friendly, knowledgeable staff and quick turnaround repair service.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "63 3rd Ave, Linden, Johannesburg",
    location_lat: -26.1443,
    location_lng: 28.0028,
    phone: "011 782 7313",
    email: "",
    website: "https://lindencycles.co.za",
    brands_stocked: [],
    services: ["Bike Sales", "Repairs", "Accessories"],
  },
  {
    name: "Westdene Cycles",
    slug: "westdene-cycles-johannesburg",
    business_type: "shop",
    description: "Established Johannesburg bicycle shop offering mountain bikes, road bikes, gravel bikes, e-bikes, lifestyle bikes and kids bikes. Full workshop service and accessories.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "Westdene, Johannesburg, Gauteng",
    location_lat: -26.1882,
    location_lng: 27.9877,
    phone: "",
    email: "",
    website: "https://westdenecycles.co.za",
    brands_stocked: [],
    services: ["Bike Sales", "Repairs", "Accessories"],
  },
  {
    name: "Complete Cyclist",
    slug: "complete-cyclist-johannesburg",
    business_type: "shop",
    description: "Specialized concept store in Johannesburg. One-stop-shop for Specialized bicycles, clothing, shoes, and accessories. Expert Retül fitting on site for road, MTB and gravel.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "Johannesburg, Gauteng",
    location_lat: -26.2041,
    location_lng: 28.0473,
    phone: "",
    email: "",
    website: "https://complete-cyclist.com",
    brands_stocked: ["Specialized", "Roval"],
    services: ["Bike Sales", "Bike Fitting", "Repairs"],
  },
  {
    name: "Trek Johannesburg Fourways",
    slug: "trek-johannesburg-fourways",
    business_type: "shop",
    description: "Official Trek Bikes retail store at Design Quarter, Fourways. Full range of Trek road, MTB, gravel, and kids bikes. Expert workshop and Bontrager accessories.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "Shop 5 Design Quarter, Leslie Ave & Winnie Mandela Drive, Fourways, 2191",
    location_lat: -26.0281,
    location_lng: 28.0107,
    phone: "",
    email: "",
    website: "https://www.trekbikes.com/za/en_ZA/retail/johannesburg_fourways/",
    brands_stocked: ["Trek", "Bontrager"],
    services: ["Bike Sales", "Repairs", "Accessories"],
  },
  {
    name: "DVH Cycles",
    slug: "dvh-cycles-johannesburg",
    business_type: "shop",
    description: "Premium bike sales and repairs in Johannesburg with professional performance bike fitting tailored to each rider's unique biomechanics. Stocks quality brands with a focus on race-ready builds.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "Johannesburg, Gauteng",
    location_lat: -26.2041,
    location_lng: 28.0473,
    phone: "",
    email: "",
    website: "https://dvhcycles.co.za",
    brands_stocked: [],
    services: ["Bike Sales", "Bike Fitting", "Repairs"],
  },
  {
    name: "Cycle Lab Rosebank",
    slug: "cycle-lab-rosebank",
    business_type: "shop",
    description: "Cycle Lab's Johannesburg Rosebank store. Premium bikes and accessories with expert workshop service and Retül fitting. Convenient Sandton access.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "Rosebank, Johannesburg, Gauteng",
    location_lat: -26.1448,
    location_lng: 28.0432,
    phone: "",
    email: "",
    website: "https://www.cyclelab.com",
    brands_stocked: ["Specialized", "Scott", "Cannondale"],
    services: ["Bike Sales", "Repairs", "Bike Fitting"],
  },

  // ─── WORKSHOP / FITTING — GAUTENG ────────────────────────────────────────
  {
    name: "Cycle-It Professional Bike Fitting",
    slug: "cycleit-bike-fitting-johannesburg",
    business_type: "service_center",
    description: "Professional bike fitting studio in Johannesburg. Science-based dynamic fitting to unlock power, improve efficiency, and make riding more comfortable. By appointment.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "Johannesburg, Gauteng",
    location_lat: -26.2041,
    location_lng: 28.0473,
    phone: "",
    email: "",
    website: "https://cycleit.co.za",
    brands_stocked: [],
    services: ["Bike Fitting", "Performance Analysis"],
  },
  {
    name: "Pro Cycling Coaching — Morné Bester",
    slug: "pro-cycling-coaching",
    business_type: "service_center",
    description: "Professional cycling coaching by Morné Bester. Personalised cycling training programs for riders of all levels. Structured plans and performance goal-setting for road and gravel.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "Johannesburg, Gauteng",
    location_lat: -26.2041,
    location_lng: 28.0473,
    phone: "",
    email: "",
    website: "https://www.procyclingcoaching.co.za",
    brands_stocked: [],
    services: ["Cycling Coaching", "Training Plans", "Performance Coaching"],
  },

  // ─── BIKE SHOPS — PRETORIA ───────────────────────────────────────────────
  {
    name: "Cycle Mania Pretoria",
    slug: "cycle-mania-pretoria",
    business_type: "shop",
    description: "Friendly Pretoria bicycle shop offering expert bike repairs, quality bicycles, accessories and more. Well-stocked for MTB, road and commuter riders. Welcoming atmosphere.",
    province: "Gauteng",
    city: "Pretoria",
    address: "Pretoria, Gauteng",
    location_lat: -25.7479,
    location_lng: 28.2293,
    phone: "",
    email: "",
    website: "https://www.cyclemaniasa.co.za",
    brands_stocked: [],
    services: ["Bike Sales", "Repairs", "Accessories"],
  },
  {
    name: "Bruce's Cycles",
    slug: "bruces-cycles-pretoria",
    business_type: "shop",
    description: "Walk-ins welcome at this Pretoria bike shop and workshop. Service turnaround 24–48 hours depending on part availability. Accessible, no-fuss repairs and sales.",
    province: "Gauteng",
    city: "Pretoria",
    address: "Pretoria, Gauteng",
    location_lat: -25.7479,
    location_lng: 28.2293,
    phone: "064 846 3333",
    email: "",
    website: "https://bruces.co.za",
    brands_stocked: [],
    services: ["Bike Sales", "Repairs"],
  },
  {
    name: "Major Cycle City",
    slug: "major-cycle-city-pretoria",
    business_type: "service_center",
    description: "On-site professional bicycle mechanic in Pretoria offering a wide range of MTB repairs and maintenance services. Specialising in complex builds and overhauls.",
    province: "Gauteng",
    city: "Pretoria",
    address: "Pretoria, Gauteng",
    location_lat: -25.7479,
    location_lng: 28.2293,
    phone: "",
    email: "",
    website: "https://www.majorcyclecity.co.za",
    brands_stocked: [],
    services: ["Repairs", "Custom Builds", "MTB Servicing"],
  },
  {
    name: "My Bicycle Mechanic",
    slug: "my-bicycle-mechanic-pretoria",
    business_type: "service_center",
    description: "Mobile bicycle service centre in Pretoria — the professional comes to you. Collection and delivery available. Full range of repairs, maintenance and servicing.",
    province: "Gauteng",
    city: "Pretoria",
    address: "Pretoria, Gauteng",
    location_lat: -25.7479,
    location_lng: 28.2293,
    phone: "",
    email: "",
    website: "https://www.mybicyclemechanic.co.za",
    brands_stocked: [],
    services: ["Mobile Mechanic", "Repairs", "Servicing", "Collection & Delivery"],
  },

  // ─── BIKE SHOPS — KZN ───────────────────────────────────────────────────
  {
    name: "Cyclesphere Cycling",
    slug: "cyclesphere-durban",
    business_type: "shop",
    description: "KZN's biggest stockist of Giant Bicycles and cycling accessories. Full range from kids bikes to performance road and MTB. Authorised Giant dealer in Durban.",
    province: "KwaZulu-Natal",
    city: "Durban",
    address: "Durban, KwaZulu-Natal",
    location_lat: -29.8587,
    location_lng: 31.0218,
    phone: "",
    email: "",
    website: "https://www.cyclesphere.co.za",
    brands_stocked: ["Giant", "Mavic"],
    services: ["Bike Sales", "Repairs", "Accessories"],
  },
  {
    name: "Leigh's Cycle Centre",
    slug: "leighs-cycle-centre-durban",
    business_type: "shop",
    description: "Passionate team of cyclists running a premium bike shop in Durban. Leigh, Susan and their team live and breathe cycling. Expert advice on road, MTB and gravel bikes.",
    province: "KwaZulu-Natal",
    city: "Durban",
    address: "Durban, KwaZulu-Natal",
    location_lat: -29.8587,
    location_lng: 31.0218,
    phone: "",
    email: "",
    website: "https://cyclecentre.co.za",
    brands_stocked: [],
    services: ["Bike Sales", "Repairs", "Bike Fitting", "Accessories"],
  },
  {
    name: "Bikeworks Hillcrest",
    slug: "bikeworks-hillcrest",
    business_type: "shop",
    description: "Hillcrest's trusted bicycle sales and repair shop. Quality selection of bikes and cycling accessories. Professional staff and great service. Renowned MTB expertise in the KZN midlands.",
    province: "KwaZulu-Natal",
    city: "Hillcrest",
    address: "Shop 13, 5 Inanda Road, Hillcrest, KwaZulu-Natal",
    location_lat: -29.7677,
    location_lng: 30.7718,
    phone: "",
    email: "",
    website: "https://bikeworks.co.za",
    brands_stocked: [],
    services: ["Bike Sales", "Repairs", "Accessories"],
  },
  {
    name: "Biket",
    slug: "biket-hillcrest",
    business_type: "shop",
    description: "Trek Bikes South Africa approved retailer and one of SA's leading online cycling stores. Based in Hillcrest, KZN. Nationwide delivery with premium customer service and expert staff.",
    province: "KwaZulu-Natal",
    city: "Hillcrest",
    address: "Hillcrest, KwaZulu-Natal",
    location_lat: -29.7677,
    location_lng: 30.7718,
    phone: "",
    email: "",
    website: "https://biket.co.za",
    brands_stocked: ["Trek", "Bontrager"],
    services: ["Bike Sales", "Repairs", "Online Orders"],
  },
  {
    name: "Republic Sport Adventure",
    slug: "republic-sport-durban-north",
    business_type: "shop",
    description: "Award-winning cycling shop in Durban North. Official Scott dealer with a service department headed by experienced mechanic Toni Pedro. Also stocks Silverback bikes.",
    province: "KwaZulu-Natal",
    city: "Durban",
    address: "Durban North, KwaZulu-Natal",
    location_lat: -29.8023,
    location_lng: 31.0264,
    phone: "",
    email: "",
    website: "https://bicyclesouth.co.za/listings/republic-sport-adventure/",
    brands_stocked: ["Scott", "Silverback"],
    services: ["Bike Sales", "Repairs"],
  },

  // ─── ONLINE RETAILERS ────────────────────────────────────────────────────
  {
    name: "Bike Addict",
    slug: "bike-addict-online",
    business_type: "shop",
    description: "South Africa's favourite online bicycle shop catering to professional racers and novices alike. Wide range of road, MTB, gravel bikes plus second-hand deals. Advanced bike fitting also available.",
    province: "Western Cape",
    city: "Cape Town",
    address: "Online — Ships Nationwide, Western Cape",
    location_lat: -33.9249,
    location_lng: 18.4241,
    phone: "",
    email: "",
    website: "https://bike-addict.co.za",
    brands_stocked: [],
    services: ["Online Sales", "Second-Hand Bikes", "Bike Fitting"],
  },
  {
    name: "OBS — Online Bicycle Shop",
    slug: "online-bicycle-shop",
    business_type: "shop",
    description: "Proudly South African online bike retailer with best-price guarantee. Quality bikes, gear and accessories with free shipping on bicycles. Fast local delivery countrywide.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "Online — Ships Nationwide",
    location_lat: -26.2041,
    location_lng: 28.0473,
    phone: "",
    email: "",
    website: "https://online-bicycle-shop.co.za",
    brands_stocked: [],
    services: ["Online Sales", "Accessories", "Gear"],
  },
  {
    name: "Buycycle",
    slug: "buycycle-online",
    business_type: "shop",
    description: "Go-to online cycling store in South Africa. Browse and order bikes, cycling gear, and accessories online with convenient nationwide shipping.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "Online — Ships Nationwide",
    location_lat: -26.2041,
    location_lng: 28.0473,
    phone: "",
    email: "",
    website: "https://www.buycycle.co.za",
    brands_stocked: [],
    services: ["Online Sales", "Road Bikes", "MTB"],
  },
  {
    name: "Decathlon South Africa",
    slug: "decathlon-south-africa",
    business_type: "shop",
    description: "International sporting goods chain with a comprehensive cycling department. Value-for-money bikes, gear and accessories. Own brands B'Twin and Van Rysel. Multiple stores nationwide.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "Multiple stores across South Africa",
    location_lat: -26.2041,
    location_lng: 28.0473,
    phone: "",
    email: "",
    website: "https://www.decathlon.co.za",
    brands_stocked: ["B'Twin", "Van Rysel", "Riverside"],
    services: ["Bike Sales", "Repairs", "Online Orders", "Accessories"],
  },
  {
    name: "BikeHub SA",
    slug: "bikehub-sa",
    business_type: "shop",
    description: "South Africa's largest cycling classified ads and community platform. Buy and sell second-hand bikes and gear. Also lists upcoming cycling events across SA.",
    province: "Western Cape",
    city: "Cape Town",
    address: "Online — Cape Town-based",
    location_lat: -33.9249,
    location_lng: 18.4241,
    phone: "",
    email: "",
    website: "https://bikehub.co.za",
    brands_stocked: [],
    services: ["Classifieds", "Second-Hand Bikes", "Events Listing"],
  },

  // ─── BRAND IMPORTERS / DISTRIBUTORS ─────────────────────────────────────
  {
    name: "Rush Sports",
    slug: "rushsports-distributor",
    business_type: "brand",
    description: "Leading bicycle brand distributor supplying in excess of 400 independent bicycle retailers across South Africa. Distributes multiple internationally recognised cycling brands.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "Johannesburg, Gauteng",
    location_lat: -26.2041,
    location_lng: 28.0473,
    phone: "",
    email: "",
    website: "https://rushsports.co.za",
    brands_stocked: [],
    services: ["Distribution", "Wholesale", "Brand Support"],
  },
  {
    name: "Dragons Sports",
    slug: "dragons-sports-distributor",
    business_type: "brand",
    description: "Established in 1989, Dragons Sports has shaped the SA cycling industry through wholesale trade of bicycles and related products. 35+ years of brand building and distribution.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "Johannesburg, Gauteng",
    location_lat: -26.2041,
    location_lng: 28.0473,
    phone: "",
    email: "",
    website: "https://www.dragons.co.za",
    brands_stocked: [],
    services: ["Distribution", "Wholesale"],
  },
  {
    name: "Paragon Technologies",
    slug: "paragon-technologies-distributor",
    business_type: "brand",
    description: "Distributor of quality bicycle parts throughout Southern Africa since 2001. Supplies components, accessories and cycling products to independent retailers across the subcontinent.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "Johannesburg, Gauteng",
    location_lat: -26.2041,
    location_lng: 28.0473,
    phone: "",
    email: "",
    website: "https://www.paragontech.co.za",
    brands_stocked: [],
    services: ["Distribution", "Components", "Wholesale"],
  },
  {
    name: "Bicycle Power Trading",
    slug: "bicycle-power-trading",
    business_type: "brand",
    description: "Premium cycling brand distributor providing exclusive access to high-quality, globally recognised cycling brands for South African retailers.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "Johannesburg, Gauteng",
    location_lat: -26.2041,
    location_lng: 28.0473,
    phone: "",
    email: "",
    website: "https://bicyclepower.co.za",
    brands_stocked: [],
    services: ["Distribution", "Premium Brands", "Wholesale"],
  },
  {
    name: "Cape Cycle Systems",
    slug: "cape-cycle-systems",
    business_type: "brand",
    description: "Over 37 years supplying, servicing and maintaining independent bicycle dealers across South Africa. A cornerstone of the SA cycling supply chain.",
    province: "Western Cape",
    city: "Cape Town",
    address: "Cape Town, Western Cape",
    location_lat: -33.9249,
    location_lng: 18.4241,
    phone: "",
    email: "",
    website: "https://www.capecycles.co.za",
    brands_stocked: [],
    services: ["Distribution", "Wholesale", "Dealer Support"],
  },
  {
    name: "Avalanche South Africa",
    slug: "avalanche-bikes-sa",
    business_type: "brand",
    description: "Supplying South Africa's favourite bicycles for over 30 years. Complete range covering entry-level to performance. Trusted local brand with national dealer network.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "Johannesburg, Gauteng",
    location_lat: -26.2041,
    location_lng: 28.0473,
    phone: "",
    email: "",
    website: "https://www.avalanchebikes.co.za",
    brands_stocked: ["Avalanche"],
    services: ["Distribution", "Retail", "Wholesale"],
  },
  {
    name: "Ballistic Bike Trading",
    slug: "ballistic-bike-trading",
    business_type: "brand",
    description: "Premier cycling importer and distributor of quality cycling sportswear and equipment. Supplies independent retailers throughout South Africa with a broad product range.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "Johannesburg, Gauteng",
    location_lat: -26.2041,
    location_lng: 28.0473,
    phone: "",
    email: "",
    website: "https://www.ballisticbiketrading.co.za",
    brands_stocked: [],
    services: ["Distribution", "Apparel", "Equipment"],
  },
  {
    name: "Giant South Africa",
    slug: "giant-south-africa",
    business_type: "brand",
    description: "Official Giant Bicycles distributor for South Africa. Full range of Giant road, MTB, gravel, e-bike and kids bicycles through authorised dealer network nationwide.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "Johannesburg, Gauteng",
    location_lat: -26.2041,
    location_lng: 28.0473,
    phone: "",
    email: "",
    website: "https://giant-bicycles.co.za",
    brands_stocked: ["Giant", "Liv"],
    services: ["Distribution", "Brand Support"],
  },
  {
    name: "Raleigh Bikes South Africa",
    slug: "raleigh-south-africa",
    business_type: "brand",
    description: "Iconic British cycling brand with a large selection of mountain bikes, aluminium bikes, e-bikes, kids bikes and accessories in South Africa. National dealer network.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "Johannesburg, Gauteng",
    location_lat: -26.2041,
    location_lng: 28.0473,
    phone: "",
    email: "",
    website: "https://raleighintl.com",
    brands_stocked: ["Raleigh"],
    services: ["Distribution", "Retail"],
  },
  {
    name: "Privateer Distribution",
    slug: "privateer-distribution",
    business_type: "brand",
    description: "Cycling brand distributor working with Miway, Investec, Standard Bank and around 200 dealers. Established network in the SA cycling trade with strong corporate partnership history.",
    province: "Western Cape",
    city: "Cape Town",
    address: "Cape Town, Western Cape",
    location_lat: -33.9249,
    location_lng: 18.4241,
    phone: "",
    email: "",
    website: "https://privateer.co.za/distribution/",
    brands_stocked: [],
    services: ["Distribution", "Corporate Partnerships"],
  },

  // ─── EVENT ORGANISERS ────────────────────────────────────────────────────
  {
    name: "Cycling South Africa (CSA)",
    slug: "cycling-south-africa",
    business_type: "event_organiser",
    description: "National governing body for road cycling, mountain biking and track cycling in South Africa. Manages the official SA cycling event calendar and federation licensing.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "Johannesburg, Gauteng",
    location_lat: -26.2041,
    location_lng: 28.0473,
    phone: "",
    email: "",
    website: "https://www.cyclingsa.com",
    brands_stocked: [],
    services: ["Event Management", "Federation", "Licensing"],
  },
  {
    name: "Dryland Event Management",
    slug: "dryland-events",
    business_type: "event_organiser",
    description: "Dryland owns and operates 11 mountain bike events across South Africa. Wide range of adventure and fitness formats for all ability levels. Premier MTB event promoter.",
    province: "Western Cape",
    city: "Cape Town",
    address: "Cape Town, Western Cape",
    location_lat: -33.9249,
    location_lng: 18.4241,
    phone: "",
    email: "",
    website: "https://dryland.co.za/cycling-events/",
    brands_stocked: [],
    services: ["MTB Events", "Adventure Events", "Event Management"],
  },
  {
    name: "Chain Gang Events",
    slug: "chaingang-events",
    business_type: "event_organiser",
    description: "Owned by Juan Botes. Specialises in organising MTB, trail running and triathlon events across South Africa. Known for technical courses and high participant satisfaction.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "Johannesburg, Gauteng",
    location_lat: -26.2041,
    location_lng: 28.0473,
    phone: "",
    email: "",
    website: "https://chaingangevents.co.za",
    brands_stocked: [],
    services: ["MTB Events", "Triathlon Events", "Event Management"],
  },
  {
    name: "Lenick Promotions",
    slug: "lenick-promotions",
    business_type: "event_organiser",
    description: "Proven record in presenting cycling and other adventure events in South Africa. Full event management from logistics to participant experience. Based in Cape Town.",
    province: "Western Cape",
    city: "Cape Town",
    address: "Cape Town, Western Cape",
    location_lat: -33.9249,
    location_lng: 18.4241,
    phone: "",
    email: "",
    website: "https://lenickpromotions.co.za",
    brands_stocked: [],
    services: ["Cycling Events", "Road Events", "MTB Events"],
  },
  {
    name: "MyActive Events",
    slug: "myactive-events",
    business_type: "event_organiser",
    description: "15 years of experience hosting South Africa's premier cycling and multi-sport events. Comprehensive event management platform with entries, race info and results.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "Johannesburg, Gauteng",
    location_lat: -26.2041,
    location_lng: 28.0473,
    phone: "",
    email: "",
    website: "https://events.myactive.co.za",
    brands_stocked: [],
    services: ["Event Management", "Online Entries", "Road Events", "MTB Events"],
  },
  {
    name: "Oryx Endurance",
    slug: "oryx-endurance",
    business_type: "event_organiser",
    description: "Dedicated to crafting unforgettable cycling experiences through professionally organised events. Enables participants of all ability levels to embrace new endurance challenges.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "Johannesburg, Gauteng",
    location_lat: -26.2041,
    location_lng: 28.0473,
    phone: "",
    email: "",
    website: "https://oryxendurance.co.za",
    brands_stocked: [],
    services: ["Endurance Events", "Gravel Events", "Road Events"],
  },
  {
    name: "Red Cherry Events",
    slug: "red-cherry-events",
    business_type: "event_organiser",
    description: "Owns and operates various mountain bike events across South Africa. Mix of competitive races and fun ride formats for all levels. Passionate event organising team.",
    province: "Western Cape",
    city: "Cape Town",
    address: "Cape Town, Western Cape",
    location_lat: -33.9249,
    location_lng: 18.4241,
    phone: "",
    email: "",
    website: "https://redcherryevents.co.za",
    brands_stocked: [],
    services: ["MTB Events", "Fun Rides", "Races"],
  },
  {
    name: "ROR Events",
    slug: "ror-events",
    business_type: "event_organiser",
    description: "Simplifies the process of joining races from mountain biking to running. Entry management, race info, and result tracking for SA cycling events.",
    province: "Western Cape",
    city: "Cape Town",
    address: "Cape Town, Western Cape",
    location_lat: -33.9249,
    location_lng: 18.4241,
    phone: "",
    email: "",
    website: "https://rorevents.co.za",
    brands_stocked: [],
    services: ["Event Management", "Online Entries", "MTB Events", "Road Events"],
  },
  {
    name: "Pedal Power Association",
    slug: "pedal-power-association",
    business_type: "event_organiser",
    description: "Founded in 1976. SA's oldest cycling advocacy group and event organiser. Public benefit organisation promoting cycling and cyclist interests. Hosts iconic Cape Town cycling events.",
    province: "Western Cape",
    city: "Cape Town",
    address: "Cape Town, Western Cape",
    location_lat: -33.9249,
    location_lng: 18.4241,
    phone: "",
    email: "",
    website: "https://pedalpower.org.za",
    brands_stocked: [],
    services: ["Events", "Advocacy", "Community Rides"],
  },
  {
    name: "Racepass",
    slug: "racepass-events",
    business_type: "event_organiser",
    description: "Comprehensive cycling events platform for South Africa covering road cycling and MTB races. Centralised entry management and race calendar for SA cyclists.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "Online — South Africa",
    location_lat: -26.2041,
    location_lng: 28.0473,
    phone: "",
    email: "",
    website: "https://racepass.com/za/cycling-events",
    brands_stocked: [],
    services: ["Event Listings", "Online Entries", "Road Events", "MTB Events"],
  },

  // ─── BIKE HIRE — GAUTENG ────────────────────────────────────────────────
  {
    name: "Curiocity Africa — Bike Rental",
    slug: "curiocity-bike-rental-johannesburg",
    business_type: "tour_operator",
    description: "Explore Johannesburg by bicycle — rental available by the hour. Based in Maboneng. Ideal for urban exploration and guided city tours on two wheels in the CBD.",
    province: "Gauteng",
    city: "Johannesburg",
    address: "Maboneng, Johannesburg, Gauteng",
    location_lat: -26.2055,
    location_lng: 28.0644,
    phone: "",
    email: "",
    website: "https://curiocity.africa/tours/bike-rental-hourly-rental/",
    brands_stocked: [],
    services: ["Bike Hire", "City Tours", "Hourly Rental"],
  },
];

async function seed() {
  console.log(`\n🚀 CrankMart Directory Seed — ${businesses.length} businesses\n`);

  let inserted = 0;
  let skipped = 0;
  let errors = 0;

  for (const b of businesses) {
    try {
      await sql.query(
        `INSERT INTO businesses (
          name, slug, business_type, description,
          province, city, address,
          location_lat, location_lng,
          phone, email, website,
          brands_stocked, services,
          is_verified, is_premium
        ) VALUES (
          $1, $2, $3::business_type, $4,
          $5, $6, $7,
          $8, $9,
          $10, $11, $12,
          $13::text[], $14::text[],
          false, false
        )
        ON CONFLICT (slug) DO NOTHING`,
        [
          b.name,
          b.slug,
          b.business_type,
          b.description,
          b.province,
          b.city,
          b.address,
          b.location_lat,
          b.location_lng,
          b.phone,
          b.email,
          b.website,
          b.brands_stocked,
          b.services,
        ]
      );

      console.log(`  ✓ ${b.name}`);
      inserted++;
    } catch (e: any) {
      if (e.message?.includes("duplicate") || e.message?.includes("23505") || e.code === "23505") {
        console.log(`  ⚠ Skip (exists): ${b.name}`);
        skipped++;
      } else {
        console.error(`  ✗ Error: ${b.name} — ${e.message}`);
        errors++;
      }
    }
  }

  console.log(`\n${"─".repeat(50)}`);
  console.log(`✅ Done: ${inserted} inserted | ${skipped} skipped | ${errors} errors`);

  // Final count
  const result = await sql`SELECT COUNT(*) as count FROM businesses`;
  console.log(`📊 Total businesses in DB: ${result[0].count}`);

  process.exit(errors > 0 ? 1 : 0);
}

seed().catch((e) => {
  console.error("Fatal:", e);
  process.exit(1);
});
