import { neon } from '@neondatabase/serverless'

async function generateSlug(title: string): Promise<string> {
  return title
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^\w-]/g, '')
    .replace(/-+/g, '-')
}

async function main() {
  const sql = neon(process.env.DATABASE_URL!)

  const eventsData = [
    {
      title: 'Absa Cape Epic',
      description: 'Africa\'s leading three-day mountain bike stage race in the Western Cape.',
      eventType: 'race',
      startDate: new Date('2026-03-12'),
      endDate: new Date('2026-03-14'),
      province: 'Western Cape',
      city: 'Wellington',
      venue: 'Wellington, WC',
      distance: '40km/stage',
      entryFee: 'R8,500',
      entryUrl: 'https://entryninja.com/events/cape-epic',
      websiteUrl: 'https://capeepic.com',
      organiserName: 'Cape Epic Organizers',
      organiserEmail: 'info@capeepic.com',
      organiserPhone: '+27 21 555 0199',
      isFeatured: true,
    },
    {
      title: 'JoBerg2C',
      description: '7-day mountain bike stage race from Johannesburg to Cape Town.',
      eventType: 'race',
      startDate: new Date('2026-11-08'),
      endDate: new Date('2026-11-15'),
      province: 'Multi-province',
      city: 'Johannesburg',
      venue: 'Johannesburg to Cape Town',
      distance: '900km',
      entryFee: 'R7,200',
      entryUrl: 'https://entryninja.com/events/joberg2c',
      websiteUrl: 'https://joberg2c.co.za',
      organiserName: 'JoBerg2C Organisers',
      organiserEmail: 'info@joberg2c.co.za',
      organiserPhone: '+27 11 555 0122',
      isFeatured: true,
    },
    {
      title: 'Attakwas Extreme',
      description: 'Multi-day mountain bike endurance race in the Attakwas Swartberg.',
      eventType: 'race',
      startDate: new Date('2026-01-30'),
      endDate: new Date('2026-02-01'),
      province: 'Western Cape',
      city: 'De Rust',
      venue: 'Attakwas, WC',
      distance: '120km',
      entryFee: 'R850',
      entryUrl: 'https://entryninja.com/events/attakwas',
      websiteUrl: 'https://attakwasextreme.co.za',
      organiserName: 'Attakwas Events',
      organiserEmail: 'info@attakwas.co.za',
      organiserPhone: '+27 44 555 0333',
      isFeatured: false,
    },
    {
      title: 'Wines2Whales',
      description: '3-day mountain bike race through the Drakenstein Mountains and valleys.',
      eventType: 'race',
      startDate: new Date('2026-11-20'),
      endDate: new Date('2026-11-22'),
      province: 'Western Cape',
      city: 'Franschhoek',
      venue: 'Franschhoek to Hermanus',
      distance: '175km total',
      entryFee: 'R4,500',
      entryUrl: 'https://entryninja.com/events/wines2whales',
      websiteUrl: 'https://wines2whales.co.za',
      organiserName: 'Wines2Whales Team',
      organiserEmail: 'info@wines2whales.co.za',
      organiserPhone: '+27 21 555 0444',
      isFeatured: true,
    },
    {
      title: 'Momentum Health Tankwa Trek',
      description: 'Ultra-distance 4-day mountain bike stage race in the Tankwa Karoo.',
      eventType: 'race',
      startDate: new Date('2026-02-19'),
      endDate: new Date('2026-02-22'),
      province: 'Western Cape',
      city: 'Clanwilliam',
      venue: 'Tankwa Karoo',
      distance: '250km+',
      entryFee: 'R5,200',
      entryUrl: 'https://entryninja.com/events/tankwa-trek',
      websiteUrl: 'https://tankwatrek.co.za',
      organiserName: 'Momentum Health',
      organiserEmail: 'info@tankwatrek.co.za',
      organiserPhone: '+27 21 555 0555',
      isFeatured: false,
    },
    {
      title: 'Cape Pioneer Trek',
      description: 'Professional 4-day point-to-point mountain bike stage race.',
      eventType: 'race',
      startDate: new Date('2026-10-08'),
      endDate: new Date('2026-10-11'),
      province: 'Western Cape',
      city: 'Villiersdorp',
      venue: 'Cape to Hermanus region',
      distance: '200km+',
      entryFee: 'R7,800',
      entryUrl: 'https://entryninja.com/events/cape-pioneer',
      websiteUrl: 'https://capepioneertrek.com',
      organiserName: 'Cape Pioneer Events',
      organiserEmail: 'info@capepioneertrek.com',
      organiserPhone: '+27 21 555 0666',
      isFeatured: true,
    },
    {
      title: 'Sani2C',
      description: '5-day mountain bike race in the Drakensberg region.',
      eventType: 'race',
      startDate: new Date('2026-05-14'),
      endDate: new Date('2026-05-18'),
      province: 'KwaZulu-Natal',
      city: 'Himeville',
      venue: 'Sani Pass region',
      distance: '240km total',
      entryFee: 'R6,500',
      entryUrl: 'https://entryninja.com/events/sani2c',
      websiteUrl: 'https://sani2c.co.za',
      organiserName: 'Sani2C Team',
      organiserEmail: 'info@sani2c.co.za',
      organiserPhone: '+27 33 555 0777',
      isFeatured: false,
    },
    {
      title: 'Absa Cape Town Cycle Tour',
      description: '109km iconic mass participation road cycling event in Cape Town.',
      eventType: 'sportive',
      startDate: new Date('2026-03-08'),
      endDate: new Date('2026-03-08'),
      province: 'Western Cape',
      city: 'Cape Town',
      venue: 'Cape Town',
      distance: '109km',
      entryFee: 'R590',
      entryUrl: 'https://entryninja.com/events/cape-town-cycle-tour',
      websiteUrl: 'https://cycletour.co.za',
      organiserName: 'ASA Events',
      organiserEmail: 'info@cycletour.co.za',
      organiserPhone: '+27 21 555 0888',
      isFeatured: true,
    },
    {
      title: '94.7 Cycle Challenge',
      description: 'Gauteng\'s premier road cycling sportive with 94km and 59km routes.',
      eventType: 'sportive',
      startDate: new Date('2026-11-07'),
      endDate: new Date('2026-11-07'),
      province: 'Gauteng',
      city: 'Johannesburg',
      venue: 'Johannesburg',
      distance: '94km',
      entryFee: 'R390',
      entryUrl: 'https://entryninja.com/events/947-cycle-challenge',
      websiteUrl: 'https://947cyclechallenge.co.za',
      organiserName: '94.7 Events',
      organiserEmail: 'info@947cyclechallenge.co.za',
      organiserPhone: '+27 11 555 0999',
      isFeatured: false,
    },
    {
      title: 'Dischem Pharmacy Race to the Sun',
      description: 'Annual cycling race from the Winelands to the coast.',
      eventType: 'race',
      startDate: new Date('2026-02-07'),
      endDate: new Date('2026-02-07'),
      province: 'Western Cape',
      city: 'Paarl',
      venue: 'Paarl to Hermanus',
      distance: '87km',
      entryFee: 'R250',
      entryUrl: 'https://entryninja.com/events/race-to-sun',
      websiteUrl: 'https://dischem.co.za/events',
      organiserName: 'Dischem Events',
      organiserEmail: 'events@dischem.co.za',
      organiserPhone: '+27 21 555 1011',
      isFeatured: false,
    },
    {
      title: 'Gravel & Tar Classic',
      description: 'Mixed-terrain gravel cycling adventure in the Western Cape.',
      eventType: 'sportive',
      startDate: new Date('2026-06-20'),
      endDate: new Date('2026-06-20'),
      province: 'Western Cape',
      city: 'Greyton',
      venue: 'Greyton area',
      distance: '68km',
      entryFee: 'R450',
      entryUrl: 'https://entryninja.com/events/gravel-tar',
      websiteUrl: 'https://graveltarclassic.co.za',
      organiserName: 'Gravel SA',
      organiserEmail: 'info@graveltarclassic.co.za',
      organiserPhone: '+27 21 555 1122',
      isFeatured: false,
    },
    {
      title: 'Rock & Rut MTB Challenge',
      description: 'Technical mountain bike race in Gauteng with challenging singletrack.',
      eventType: 'race',
      startDate: new Date('2026-07-18'),
      endDate: new Date('2026-07-18'),
      province: 'Gauteng',
      city: 'Roodepoort',
      venue: 'Cradle MTB Park',
      distance: '45km',
      entryFee: 'R350',
      entryUrl: 'https://entryninja.com/events/rock-rut',
      websiteUrl: 'https://rockrut.co.za',
      organiserName: 'Rock & Rut Events',
      organiserEmail: 'info@rockrut.co.za',
      organiserPhone: '+27 11 555 1233',
      isFeatured: false,
    },
    {
      title: 'Karoo to Coast',
      description: 'Scenic road cycling race from the Karoo plateau to the coast.',
      eventType: 'race',
      startDate: new Date('2026-08-15'),
      endDate: new Date('2026-08-15'),
      province: 'Eastern Cape',
      city: 'Grahamstown',
      venue: 'Grahamstown to Hermanus',
      distance: '156km',
      entryFee: 'R480',
      entryUrl: 'https://entryninja.com/events/karoo-coast',
      websiteUrl: 'https://karoocoast.co.za',
      organiserName: 'Karoo to Coast Events',
      organiserEmail: 'info@karoocoast.co.za',
      organiserPhone: '+27 46 555 1344',
      isFeatured: false,
    },
    {
      title: 'Amashova Classic',
      description: '106km iconic road cycling race in KwaZulu-Natal.',
      eventType: 'sportive',
      startDate: new Date('2026-10-24'),
      endDate: new Date('2026-10-24'),
      province: 'KwaZulu-Natal',
      city: 'Durban',
      venue: 'Durban area',
      distance: '106km',
      entryFee: 'R320',
      entryUrl: 'https://entryninja.com/events/amashova',
      websiteUrl: 'https://amashova.co.za',
      organiserName: 'Amashova Events',
      organiserEmail: 'info@amashova.co.za',
      organiserPhone: '+27 31 555 1455',
      isFeatured: false,
    },
    {
      title: 'Berg & Bush MTB',
      description: '3-day mountain bike stage race in the Drakensberg region.',
      eventType: 'race',
      startDate: new Date('2026-09-11'),
      endDate: new Date('2026-09-13'),
      province: 'KwaZulu-Natal',
      city: 'Bergville',
      venue: 'Drakensberg mountains',
      distance: '110km total',
      entryFee: 'R1,200',
      entryUrl: 'https://entryninja.com/events/berg-bush',
      websiteUrl: 'https://bergandbush.co.za',
      organiserName: 'Berg & Bush Events',
      organiserEmail: 'info@bergandbush.co.za',
      organiserPhone: '+27 36 555 1566',
      isFeatured: false,
    },
  ]

  for (const event of eventsData) {
    const slug = await generateSlug(event.title)
    try {
      await sql`
        INSERT INTO events (
          title, slug, description, event_type, status,
          start_date, end_date, province, city, venue,
          distance, entry_fee, entry_url, website_url,
          organiser_name, organiser_email, organiser_phone,
          is_featured, moderation_status, is_scraped
        ) VALUES (
          ${event.title}, ${slug}, ${event.description}, ${event.eventType}, 'pending_review',
          ${event.startDate}, ${event.endDate}, ${event.province}, ${event.city}, ${event.venue},
          ${event.distance}, ${event.entryFee}, ${event.entryUrl}, ${event.websiteUrl},
          ${event.organiserName}, ${event.organiserEmail}, ${event.organiserPhone},
          ${event.isFeatured}, 'approved', false
        )
      `
      console.log(`✅ Created: ${event.title}`)
    } catch (err) {
      console.error(`❌ Error creating ${event.title}:`, err)
    }
  }

  console.log('✅ Seeding complete: 15 events created')
  process.exit(0)
}

main().catch(e => { console.error(e); process.exit(1) })
