import { neon } from '@neondatabase/serverless';
const sql = neon(process.env.DATABASE_URL!);

const fsEvents = [
  {
    title: 'Race2TheSky',
    slug: 'race2thesky-2026',
    description: 'The ultimate gravel biking adventure in the Eastern Free State. Starting from Uitzicht Game Lodge, Fouriesburg, with the dramatic Lesotho border mountains as backdrop. Three distances: Dash (35km), Quest (87km), 100 Miler (165km). E-bikes welcome. Part of the Oryx Endurance circuit.',
    event_type: 'stage_race',
    city: 'Fouriesburg',
    province: 'Free State',
    venue_name: 'Uitzicht Game Lodge',
    event_date_start: '2026-02-07',
    event_date_end: '2026-02-07',
    entry_url: 'https://oryxendurance.co.za/page33.html',
    entry_status: 'open',
    organiser_name: 'Oryx Endurance',
    organiser_website: 'https://oryxendurance.co.za',
    discipline: 'gravel',
    distance: '35km / 87km / 165km',
    is_featured: false,
    cover_image_url: 'https://crankmart.com/uploads/events/race2thesky-2026.jpg',
  },
  {
    title: 'Munga Grit: Trans Xhariep',
    slug: 'munga-grit-trans-xhariep-2026',
    description: 'A Munga ultra-endurance MTB event circling South Africa\'s largest dam — the Gariep. The 50hr/500km flagship event is one of the most brutal in SA. Also 70km and 160km distances. Set at the Orange River\'s most dramatic point at 1,300m elevation. March 20–22, 2026.',
    event_type: 'stage_race',
    city: 'Gariep Dam',
    province: 'Free State',
    venue_name: 'Gariep Dam',
    event_date_start: '2026-03-20',
    event_date_end: '2026-03-22',
    entry_url: 'https://themunga.com/munga-grit-trans-xhariep',
    entry_status: 'open',
    organiser_name: 'The Munga',
    organiser_website: 'https://themunga.com',
    discipline: 'gravel',
    distance: '70km / 160km / 500km',
    is_featured: false,
    cover_image_url: 'https://crankmart.com/uploads/events/munga-trans-xhariep-2026.jpg',
  },
  {
    title: 'The MATSA',
    slug: 'the-matsa-2026',
    description: 'Part of the Oryx Endurance gravel series — an adventure ride from Kandirri Game Lodge in the Free State. Dash (35km), Quest (87km), and 100 Miler (165km) options. E-bikes welcome. Spectacular open Free State landscape. March 28, 2026.',
    event_type: 'race',
    city: 'Free State',
    province: 'Free State',
    venue_name: 'Kandirri Game Lodge',
    event_date_start: '2026-03-28',
    event_date_end: '2026-03-28',
    entry_url: 'https://oryxendurance.co.za',
    entry_status: 'open',
    organiser_name: 'Oryx Endurance',
    organiser_website: 'https://oryxendurance.co.za',
    discipline: 'gravel',
    distance: '35km / 87km / 165km',
    is_featured: false,
    cover_image_url: 'https://crankmart.com/uploads/events/the-matsa-2026.jpg',
  },
  {
    title: 'Gravel Rush: Lion and Tiger Edition',
    slug: 'gravel-rush-lion-and-tiger-2026',
    description: 'Epic gravel ultra held at Boskoppie Lion and Tiger Reserve near Kroonstad, Free State. Routes of 165km and 265km across vast Free State plains in a unique game reserve setting. Organised by The Munga. April 11, 2026.',
    event_type: 'race',
    city: 'Kroonstad',
    province: 'Free State',
    venue_name: 'Boskoppie Lion and Tiger Reserve',
    event_date_start: '2026-04-11',
    event_date_end: '2026-04-11',
    entry_url: 'https://themunga.com',
    entry_status: 'open',
    organiser_name: 'The Munga',
    organiser_website: 'https://themunga.com',
    discipline: 'gravel',
    distance: '165km / 265km',
    is_featured: false,
    cover_image_url: 'https://crankmart.com/uploads/events/gravel-rush-lion-tiger-2026.jpg',
  },
  {
    title: 'Sandstone Unbound',
    slug: 'sandstone-unbound-2026',
    description: 'A 4-day, 270km supported gravel adventure through the ancient Witteberge mountains of the Eastern Free State. Non-competitive, open to MTB and gravel bikes. Five nights accommodation at Uitzicht Private Game Reserve included. Spectacular Lesotho-border terrain. April 23–27, 2026.',
    event_type: 'stage_race',
    city: 'Fouriesburg',
    province: 'Free State',
    venue_name: 'Uitzicht Private Game Reserve',
    event_date_start: '2026-04-23',
    event_date_end: '2026-04-27',
    entry_url: 'https://www.oryxendurance.co.za/page13.html',
    entry_status: 'open',
    organiser_name: 'Oryx Endurance',
    organiser_website: 'https://oryxendurance.co.za',
    discipline: 'gravel',
    distance: '270km (4 days)',
    is_featured: false,
    cover_image_url: 'https://crankmart.com/uploads/events/sandstone-unbound-2026.jpg',
  },
  {
    title: 'Golden Gate MTB Challenge',
    slug: 'golden-gate-mtb-2026',
    description: 'MTB and trail run event in the spectacular Golden Gate Highlands National Park near Clarens. Routes of 22km and 44km explore the park\'s iconic golden sandstone cliffs and mountain landscapes. Family-friendly, great cause. May 1, 2026.',
    event_type: 'race',
    city: 'Clarens',
    province: 'Free State',
    venue_name: 'Golden Gate Highlands National Park',
    event_date_start: '2026-05-01',
    event_date_end: '2026-05-01',
    entry_url: 'https://events.myactive.co.za',
    entry_status: 'open',
    organiser_name: 'MyActive Events',
    organiser_website: 'https://events.myactive.co.za',
    discipline: 'mtb',
    distance: '22km / 44km',
    is_featured: false,
    cover_image_url: 'https://crankmart.com/uploads/events/golden-gate-mtb-2026.jpg',
  },
  {
    title: 'Sungazer 100 Miler',
    slug: 'sungazer-2026',
    description: 'Part of the Oryx Endurance Free State circuit — an MTB/gravel adventure with Dash (44km) and Quest (87km) options. Based at Tiffany\'s Function Venue. Open to e-bikes. Classic rolling Free State landscape. May 30, 2026.',
    event_type: 'race',
    city: 'Free State',
    province: 'Free State',
    venue_name: "Tiffany's Function Venue",
    event_date_start: '2026-05-30',
    event_date_end: '2026-05-30',
    entry_url: 'https://oryxendurance.co.za',
    entry_status: 'open',
    organiser_name: 'Oryx Endurance',
    organiser_website: 'https://oryxendurance.co.za',
    discipline: 'gravel',
    distance: '44km / 87km',
    is_featured: false,
    cover_image_url: 'https://crankmart.com/uploads/events/sungazer-2026.jpg',
  },
  {
    title: 'Race2TheKaroo',
    slug: 'race2thekaroo-2026',
    description: 'A gravel adventure in the Northern Free State / Karoo border region, based at Klipkraal Farm Stall. Dash (46km), Quest (85km), and 100 Miler (165km) distances. Part of the Oryx Endurance circuit. E-bikes welcome. August 29, 2026.',
    event_type: 'race',
    city: 'Free State',
    province: 'Free State',
    venue_name: 'Klipkraal Farm Stall',
    event_date_start: '2026-08-29',
    event_date_end: '2026-08-29',
    entry_url: 'https://oryxendurance.co.za',
    entry_status: 'open',
    organiser_name: 'Oryx Endurance',
    organiser_website: 'https://oryxendurance.co.za',
    discipline: 'gravel',
    distance: '46km / 85km / 165km',
    is_featured: false,
    cover_image_url: 'https://crankmart.com/uploads/events/race2thekaroo-2026.jpg',
  },
  {
    title: 'Battle of the Bikes',
    slug: 'battle-of-the-bikes-2026',
    description: 'A gravel and e-bike challenge based at Jacobsdal Inn in the Northern Cape / Free State border region. 140km route through remote Karoo plains. Unique desert landscape event. October 3, 2026.',
    event_type: 'race',
    city: 'Jacobsdal',
    province: 'Free State',
    venue_name: 'Jacobsdal Inn',
    event_date_start: '2026-10-03',
    event_date_end: '2026-10-03',
    entry_url: 'https://oryxendurance.co.za',
    entry_status: 'open',
    organiser_name: 'Oryx Endurance',
    organiser_website: 'https://oryxendurance.co.za',
    discipline: 'gravel',
    distance: '140km',
    is_featured: false,
    cover_image_url: 'https://crankmart.com/uploads/events/battle-of-the-bikes-2026.jpg',
  },
  {
    title: 'Zuikerkop MTB Challenge',
    slug: 'zuikerkop-mtb-2026',
    description: 'Annual MTB challenge based at Zuikerkop Country Game Lodge, Clocolan in the Free State. Routes of 6km to 60km suit all levels from families to serious riders. Set in the scenic eastern Free State foothills. October 10, 2026.',
    event_type: 'race',
    city: 'Clocolan',
    province: 'Free State',
    venue_name: 'Zuikerkop Country Game Lodge',
    event_date_start: '2026-10-10',
    event_date_end: '2026-10-10',
    entry_url: 'https://events.myactive.co.za',
    entry_status: 'open',
    organiser_name: 'MyActive Events',
    organiser_website: 'https://events.myactive.co.za',
    discipline: 'mtb',
    distance: '6km / 11km / 16km / 20km / 30km / 60km',
    is_featured: false,
    cover_image_url: 'https://crankmart.com/uploads/events/zuikerkop-mtb-2026.jpg',
  },
];

async function main() {
  // Check what columns events table has
  const cols = await sql`SELECT column_name FROM information_schema.columns WHERE table_name='events' ORDER BY ordinal_position` as any[];
  const colNames = cols.map((c: any) => c.column_name);
  console.log('Events columns:', colNames.join(', '));
  console.log('');

  let added = 0, skipped = 0;
  for (const e of fsEvents) {
    const exists = await sql`SELECT id FROM events WHERE slug = ${e.slug}`;
    if (exists.length) { console.log('SKIP:', e.title); skipped++; continue; }
    
    await sql`
      INSERT INTO events (title, slug, description, event_type, city, province, venue_name,
        event_date_start, event_date_end, entry_url, entry_status, organiser_name, organiser_website,
        discipline, is_featured, cover_image_url, status, created_at, updated_at)
      VALUES (
        ${e.title}, ${e.slug}, ${e.description}, ${e.event_type}, ${e.city}, ${e.province},
        ${e.venue_name}, ${e.event_date_start}::date, ${e.event_date_end}::date,
        ${e.entry_url}, ${e.entry_status}, ${e.organiser_name}, ${e.organiser_website},
        ${e.discipline}, ${e.is_featured}, ${e.cover_image_url},
        'pending_review', NOW(), NOW()
      )
    `;
    console.log('ADDED:', e.title, '|', e.city, '|', e.event_date_start);
    added++;
  }

  console.log(`\nDone: ${added} added, ${skipped} skipped`);
  const total = await sql`SELECT province, COUNT(*) as c FROM events GROUP BY province ORDER BY c DESC` as any[];
  console.log('\nEvents by province:');
  total.forEach((r: any) => console.log(`  ${r.province || 'Unknown'}: ${r.c}`));
}
main().catch(console.error);
