import { neon } from '@neondatabase/serverless';
const sql = neon(process.env.DATABASE_URL!);

const events = [
  {
    title: 'The Herald Ultimate Quest',
    slug: 'herald-ultimate-quest-2026',
    type: 'race',
    city: 'Addo',
    province: 'Eastern Cape',
    venue: 'Addo',
    start: '2026-02-08', end: '2026-02-08',
    entry: 'https://www.racespace.co.za/race/5768-the-herald-ultimate-quest',
    organiser: 'The Herald Events',
    org_web: 'https://events.myactive.co.za',
    distance: '5km / 15km / 30km / 60km / 186km',
    desc: 'Multi-discipline adventure event near Addo in the Eastern Cape. Five distances from 5km to a 186km ultimate challenge combining MTB, trail running, and road cycling. Set in the beautiful Addo area with Big 5 game reserve as backdrop. February 8, 2026.',
  },
  {
    title: 'Ride The Karoo — 50 Miler',
    slug: 'ride-the-karoo-50-miler-2026',
    type: 'race',
    city: 'Middelburg EC',
    province: 'Eastern Cape',
    venue: 'Dwarsvlei Farm',
    start: '2026-02-22', end: '2026-02-22',
    entry: 'https://ridethekaroo.co.za',
    organiser: 'Ride The Karoo',
    org_web: 'https://ridethekaroo.co.za',
    distance: '80km / 160km',
    desc: 'Single-day Karoo MTB challenge at Dwarsvlei Farm, Middelburg EC. The 80km (50 Miler) and 160km routes tackle authentic Karoo terrain — sheep tracks, stone walls, windpumps and vast open plains. A taste of the full Ride the Karoo experience. February 22, 2026.',
  },
  {
    title: 'Forest Boogie',
    slug: 'forest-boogie-2026',
    type: 'stage_race',
    city: 'Hogsback',
    province: 'Eastern Cape',
    venue: 'Arminel Lodge, Hogsback',
    start: '2026-03-13', end: '2026-03-15',
    entry: 'https://forestboogie.co.za',
    organiser: 'Red Cherry Events',
    org_web: 'https://redcherryevents.co.za',
    distance: '63km / 98km (2-day stage)',
    desc: 'The reimagined Forest Boogie returns to the mystical, moss-draped forests of Hogsback in the Amatola Mountains. Red Cherry Events presents a 2-day MTB stage race through ancient indigenous forest, breathtaking viewpoints, and world-class singletrack. Gold and Silver route classes. Based at Arminel Lodge. March 13–15, 2026.',
  },
  {
    title: 'Bay by Bike MTB Race',
    slug: 'bay-by-bike-2026',
    type: 'race',
    city: 'Gqeberha',
    province: 'Eastern Cape',
    venue: 'Baywest Mall',
    start: '2026-03-22', end: '2026-03-22',
    entry: 'https://events.myactive.co.za',
    organiser: 'MyActive Events',
    org_web: 'https://events.myactive.co.za',
    distance: '5km / 10km / 20km / 40km',
    desc: 'Annual MTB race and trail run at Baywest Mall, Gqeberha (Port Elizabeth). Community-focused event exploring the coastal trails and green corridors of the Bay. Four accessible distances from 5km to 40km for all fitness levels. March 22, 2026.',
  },
  {
    title: 'Tour de Addo — Best of Darlington',
    slug: 'tour-de-addo-darlington-2026',
    type: 'race',
    city: 'Jansenville',
    province: 'Eastern Cape',
    venue: 'Darlington Dam',
    start: '2026-03-25', end: '2026-03-25',
    entry: 'https://events.myactive.co.za',
    organiser: 'Tour de Addo',
    org_web: 'https://events.myactive.co.za',
    distance: '100km',
    desc: 'Premium 100km MTB experience around the spectacular Darlington Dam near Jansenville in the Eastern Cape Karoo. Scenic Karoo route through game-rich landscapes near Addo Elephant National Park. Small, exclusive field for a quality riding experience. March 25, 2026.',
  },
  {
    title: 'Ride The Karoo — 3-Day Stage Race',
    slug: 'ride-the-karoo-3-day-2026',
    type: 'stage_race',
    city: 'Middelburg EC',
    province: 'Eastern Cape',
    venue: 'Dwarsvlei Farm',
    start: '2026-04-10', end: '2026-04-12',
    entry: 'https://ridethekaroo.co.za',
    organiser: 'Ride The Karoo',
    org_web: 'https://ridethekaroo.co.za',
    distance: '94km / 138km over 3 days',
    desc: 'The full Ride The Karoo 3-day MTB stage race experience at Dwarsvlei Farm, Middelburg EC. Routes past 100-year-old stables, ancient stone walls, sheep tracks, and windpumps. Authentic Karoo hospitality — braais, farm bread, koeksisters, condensed milk coffee under starlit skies. April 10–12, 2026.',
  },
  {
    title: 'Nieu Bethesda MTB',
    slug: 'nieu-bethesda-mtb-2026',
    type: 'race',
    city: 'Nieu-Bethesda',
    province: 'Eastern Cape',
    venue: 'Ganora Guestfarm',
    start: '2026-04-19', end: '2026-04-19',
    entry: 'https://events.myactive.co.za',
    organiser: 'MyActive Events',
    org_web: 'https://events.myactive.co.za',
    distance: '28km / 42km / 68km / 96km / 230km',
    desc: 'MTB event in the remote and extraordinary Karoo village of Nieu-Bethesda, based at Ganora Guestfarm. Five distances from 28km to an epic 230km through the dramatic Sneeuberg mountains and Karoo plains surrounding one of SA\'s most unique cultural villages. April 19, 2026.',
  },
  {
    title: 'The Owl Route — 3-Day Experience',
    slug: 'owl-route-3-day-2026',
    type: 'stage_race',
    city: 'Nieu-Bethesda',
    province: 'Eastern Cape',
    venue: 'Nieu-Bethesda',
    start: '2026-04-24', end: '2026-04-26',
    entry: 'https://www.racespace.co.za/race/6324-the-owl-route-3-day-experience',
    organiser: 'Owl Route Events',
    org_web: 'https://events.myactive.co.za',
    distance: '139km over 3 days',
    desc: 'A premium 3-day 139km guided MTB adventure through the ancient Sneeuberg mountains and Nieu-Bethesda Karoo landscape. E-bike friendly. Self-contained adventure with accommodation and full support included. A unique journey through one of the most remote corners of the Eastern Cape. April 24–26, 2026.',
  },
  {
    title: 'Zest Fruit Trans Elands 100',
    slug: 'trans-elands-100-2026',
    type: 'race',
    city: "Jeffrey's Bay",
    province: 'Eastern Cape',
    venue: 'The Ferry Hotel, Sarah Baartman',
    start: '2026-05-09', end: '2026-05-09',
    entry: 'https://events.myactive.co.za',
    organiser: 'MyActive Events',
    org_web: 'https://events.myactive.co.za',
    distance: '100km',
    desc: 'A 100km MTB race through the Elands River valley near Jeffrey\'s Bay, starting at The Ferry Hotel. Fast, scenic route through farmlands and coastal vegetation. Popular Eastern Cape century challenge held annually in May.',
  },
  {
    title: 'Grahamstown to Sea MTB (G2C)',
    slug: 'g2c-grahamstown-to-sea-2026',
    type: 'race',
    city: 'Port Alfred',
    province: 'Eastern Cape',
    venue: 'Port Alfred Country Club',
    start: '2026-06-28', end: '2026-06-28',
    entry: 'https://www.racespace.co.za/race/6439-buco-grahamstown-to-sea-mtb-race-g2c',
    organiser: 'BUCO Events',
    org_web: 'https://events.myactive.co.za',
    distance: '58km / 70km',
    desc: 'The BUCO Grahamstown to Sea (G2C) MTB Race — a beloved Eastern Cape institution riding from the historic town of Makhanda (Grahamstown) to the sea at Port Alfred. 58km and 70km route options through rolling Eastern Cape countryside. Great community atmosphere. June 28, 2026.',
  },
  {
    title: 'Glacier Storms River Traverse',
    slug: 'glacier-storms-river-traverse-2026',
    type: 'stage_race',
    city: 'Storms River',
    province: 'Eastern Cape',
    venue: 'Tsitsikamma Village Inn',
    start: '2026-07-31', end: '2026-07-31',
    entry: 'https://www.racespace.co.za/race/6441-glacier-storms-river-traverse',
    organiser: 'Dryland Event Management',
    org_web: 'https://dryland.co.za',
    distance: '158km',
    desc: 'A spectacular 158km MTB experience along the Tsitsikamma coastline near Storms River. Organised by Dryland Event Management. Set in ancient indigenous forest, coastal cliffs, and dramatic fynbos terrain of the Eastern Cape\'s Garden Route. Based at Tsitsikamma Village Inn. July 31, 2026.',
  },
  {
    title: 'Trans Baviaans',
    slug: 'trans-baviaans-2026',
    type: 'race',
    city: 'Willowmore',
    province: 'Eastern Cape',
    venue: 'Willowmore',
    start: '2026-08-08', end: '2026-08-08',
    entry: 'https://www.racespace.co.za/race/6450-trans-baviaans',
    organiser: 'Trans Baviaans Events',
    org_web: 'https://www.transbaviaans.co.za',
    distance: '230km',
    desc: 'One of South Africa\'s greatest one-day MTB endurance challenges — Trans Baviaans is a 230km single-stage race through the rugged Baviaans Kloof World Heritage Site from Willowmore to Jeffreys Bay. Brutal switchbacks, river crossings, and massive elevation through the untamed Eastern Cape wilderness. August 8, 2026.',
  },
  {
    title: 'Tour de Addo — Best of Nyathi',
    slug: 'tour-de-addo-nyathi-2026',
    type: 'race',
    city: 'Addo',
    province: 'Eastern Cape',
    venue: 'Addo Elephant National Park',
    start: '2026-08-19', end: '2026-08-19',
    entry: 'https://www.racespace.co.za/race/6454-tour-de-addo-best-of-nyathi',
    organiser: 'Tour de Addo',
    org_web: 'https://events.myactive.co.za',
    distance: '100km',
    desc: 'Premium 100km MTB experience inside Addo Elephant National Park — the Best of Nyathi edition. Ride through one of SA\'s great game reserves with potential Big 5 encounters. Exclusive small-field event through pristine game reserve terrain. August 19, 2026.',
  },
  {
    title: 'Jansenville MTB Challenge',
    slug: 'jansenville-mtb-2026',
    type: 'race',
    city: 'Jansenville',
    province: 'Eastern Cape',
    venue: 'Jansenville',
    start: '2026-09-12', end: '2026-09-12',
    entry: 'https://events.myactive.co.za',
    organiser: 'MyActive Events',
    org_web: 'https://events.myactive.co.za',
    distance: '5km / 9km / 16km / 18km / 35km / 68km / 85km',
    desc: 'Annual MTB challenge in Jansenville, a charming Karoo town in the Eastern Cape. Seven distances from 5km family rides to 85km. Set in the scenic semi-desert Karoo landscape with sweeping plains and dramatic Sneeuberg mountains as backdrop. September 12, 2026.',
  },
];

async function main() {
  let added = 0, skipped = 0;
  for (const e of events) {
    const exists = await sql`SELECT id FROM events WHERE slug = ${e.slug}`;
    if (exists.length) { console.log('SKIP:', e.title); skipped++; continue; }
    const cover = `https://crankmart.com/uploads/events/${e.slug}.jpg?v=20260330`;
    await sql`
      INSERT INTO events (
        title, slug, description, event_type, city, province, venue_name,
        event_date_start, event_date_end, entry_url, entry_status, organiser_name,
        organiser_website, discipline, distance, is_featured, cover_image_url,
        status, country, created_at, updated_at
      ) VALUES (
        ${e.title}, ${e.slug}, ${e.desc}, ${e.type}::event_type,
        ${e.city}, ${e.province}, ${e.venue},
        ${e.start}::date, ${e.end}::date,
        ${e.entry}, 'open', ${e.organiser}, ${e.org_web},
        ARRAY[${e.title}], ${e.distance},
        false, ${cover}, 'pending_review', 'ZA', NOW(), NOW()
      )
    `;
    console.log('ADDED:', e.title, '|', e.city, '|', e.start);
    added++;
  }
  console.log(`\nDone: ${added} added, ${skipped} skipped`);
  const byProv = await sql`SELECT province, COUNT(*) as c FROM events WHERE status='pending_review' GROUP BY province ORDER BY c DESC` as any[];
  console.log('\nFull calendar:');
  byProv.forEach((r: any) => console.log(`  ${r.province || 'unset'}: ${r.c}`));
}
main().catch(console.error);
